import type { Ability, BindAssignment, GameMode, Slot } from '@/core/model/ability'
import type { AbilityCategory } from '@/core/model/ability-category'
import type { HardwareConfig } from '@/core/model/hardware'
import type { SpellTextShard } from '@/core/model/snapshot'
import { buildKeyboardGeometry, isBindableKey } from '@/core/hardware/keyboards'
import { MOVEMENT_SCHEMES } from '@/core/hardware/movement-schemes'
import { MOUSE_BUTTONS, WHEEL_BUTTONS } from '@/core/hardware/mice'
import type { ZeroSpellLabels } from '@/lib/data'
import { zeroSpellLabel } from '@/lib/data'
import { BAR_SIZE, KEY_POSITION_INDEX, buildPlacementPlan } from '@/lib/placement'
import type { PlannedBind } from '@/lib/placement'

export const ADDON_UI_KEYS = [
  'optionsTitle',
  'colorsLabel',
  'colorsTooltip',
  'legendLabel',
  'legendTooltip',
  'mainbarLabel',
  'mainbarTooltip',
  'autoApplyLabel',
  'autoApplyTooltip',
  'mouseoverLabel',
  'mouseoverTooltip',
  'openBrowser',
  'applyNow',
  'browserTitle',
  'profilesHeader',
  'applyButton',
  'appliedTag',
  'activeTag',
  'keysOnlyHeader',
  'unknownTag',
  'specMismatch',
  'msgApplied',
  'msgBoundOnly',
  'msgSkipped',
  'msgIntact',
  'msgCombat',
  'msgSpecSkip',
  'enableBarsHint',
  'msgBarsEnabled',
  'msgBarsManual',
  'msgCleared',
  'msgProfile',
  'msgCheckOk',
  'msgCheckDrift',
  'msgAuto',
  'msgMouseover',
  'msgColors',
  'msgLegend',
  'msgMainbar',
  'msgSpecAdapted',
  'msgSpecSwitched',
  'msgAccountBinds',
  'viewKeyboard',
  'viewBars',
  'layerBase',
  'historyHeader',
  'backupSave',
  'backupAuto',
  'backupManual',
  'restoreButton',
  'msgBackupSaved',
  'msgRestored',
  'forceButton',
  'checkButton',
  'barsButton',
  'clearMainButton',
  'importButton',
  'importTitle',
  'importHint',
  'importAccept',
  'importCancel',
  'importedTag',
  'msgImported',
  'importErrFormat',
  'importErrChecksum',
  'importErrClient',
  'stateOn',
  'stateOff',
  'help',
] as const

export type AddonUiKey = (typeof ADDON_UI_KEYS)[number]

export interface AddonLocaleStrings {
  categories: Record<AbilityCategory, string>
  ui: Record<AddonUiKey, string>
}

export interface AddonDecor {
  colorByCategory: Record<AbilityCategory, string>
  ru: AddonLocaleStrings
  en: AddonLocaleStrings
}

const WOW_KEY_BY_KEY_ID: Record<string, string> = {
  Backquote: '`',
  Minus: '-',
  Equal: '=',
  Tab: 'TAB',
  CapsLock: 'CAPSLOCK',
  Space: 'SPACE',
  BracketLeft: '[',
  BracketRight: ']',
  Semicolon: ';',
  Quote: "'",
  Comma: ',',
  Period: '.',
  Slash: '/',
  Mouse4: 'BUTTON4',
  Mouse5: 'BUTTON5',
  WheelUp: 'MOUSEWHEELUP',
  WheelDown: 'MOUSEWHEELDOWN',
}

function wowKeyForKeyId(keyId: string): string {
  const mapped = WOW_KEY_BY_KEY_ID[keyId]
  if (mapped !== undefined) return mapped
  if (keyId.startsWith('Key')) return keyId.slice(3)
  if (keyId.startsWith('Digit')) return keyId.slice(5)
  if (keyId.startsWith('MouseG')) return `BUTTON${Number(keyId.slice(6)) + 5}`
  return keyId.toUpperCase()
}

export function wowKeyName(slot: Slot): string {
  const key = wowKeyForKeyId(slot.keyId)
  const prefix =
    slot.modifier === 'shift'
      ? 'SHIFT-'
      : slot.modifier === 'ctrl'
        ? 'CTRL-'
        : slot.modifier === 'alt'
          ? 'ALT-'
          : ''
  return `${prefix}${key}`
}

export interface AddonKeyboardKey {
  k: string
  label: string
  x: number
  w: number
  m?: boolean
}

export type AddonKeyboardRow = AddonKeyboardKey[]

export function buildAddonKeyboard(hardware: HardwareConfig): AddonKeyboardRow[] {
  const scheme = MOVEMENT_SCHEMES[hardware.movementScheme]
  const movement = new Set(scheme.movementKeyIds)
  const banned = new Set(hardware.bannedKeyIds)
  const keys = buildKeyboardGeometry(hardware.formFactor, hardware.layout)
  const rowsByY = new Map<number, AddonKeyboardRow>()
  for (const key of keys) {
    const row = rowsByY.get(key.y) ?? []
    row.push({
      k: wowKeyForKeyId(key.id),
      label: key.label,
      x: Math.round(key.x * 10),
      w: Math.round(key.w * 10),
      m: movement.has(key.id) || banned.has(key.id) || !isBindableKey(key) || undefined,
    })
    rowsByY.set(key.y, row)
  }
  const rows = [...rowsByY.entries()]
    .sort((a, b) => a[0] - b[0])
    .map(([, row]) => row.sort((a, b) => a.x - b.x))
  const mouseButtons = [
    ...MOUSE_BUTTONS[hardware.mouse],
    ...(hardware.includeMouseWheel ? WHEEL_BUTTONS : []),
  ].filter((button) => !banned.has(button.id))
  if (mouseButtons.length > 0) {
    rows.push(
      mouseButtons.map((button, index) => ({
        k: wowKeyForKeyId(button.id),
        label: button.label,
        x: index * 12,
        w: 10,
      })),
    )
  }
  return rows
}

export interface ExportBind {
  ability: Ability
  slot: Slot
  name: string
  wowKey: string
}

const MODIFIER_RANK: Record<string, number> = { none: 0, shift: 1, ctrl: 2, alt: 3 }

function bindOrder(bind: ExportBind): [number, number] {
  return [
    MODIFIER_RANK[bind.slot.modifier] ?? 9,
    KEY_POSITION_INDEX.get(bind.slot.keyId) ?? 999,
  ]
}

function compareBinds(a: ExportBind, b: ExportBind): number {
  const [modA, keyA] = bindOrder(a)
  const [modB, keyB] = bindOrder(b)
  return modA - modB || keyA - keyB
}

export function buildExportBinds(
  assignments: BindAssignment[],
  abilities: Ability[],
  slots: Slot[],
  spells: SpellTextShard,
  labels: ZeroSpellLabels,
): ExportBind[] {
  const abilityById = new Map(abilities.map((ability) => [ability.id, ability]))
  const slotById = new Map(slots.map((slot) => [slot.id, slot]))
  const binds: ExportBind[] = []
  for (const assignment of assignments) {
    const ability = abilityById.get(assignment.abilityId)
    const slot = slotById.get(assignment.slotId)
    if (!ability || !slot) continue
    const name =
      ability.spellId === 0
        ? zeroSpellLabel(ability.id, labels)
        : (spells[String(ability.spellId)]?.name ?? `#${ability.spellId}`)
    binds.push({ ability, slot, name, wowKey: wowKeyName(slot) })
  }
  return binds.sort(compareBinds)
}

export function renderPlainList(binds: ExportBind[]): string {
  const width = Math.max(...binds.map((bind) => bind.wowKey.length), 4)
  return binds
    .map((bind) => {
      const variant =
        bind.ability.variantKind === 'base' || bind.ability.category === 'targeting'
          ? ''
          : ` [@${variantTarget(bind.ability.variantKind)}]`
      return `${bind.wowKey.padEnd(width)}  ${bind.name}${variant}`
    })
    .join('\n')
}

function variantTarget(kind: string): string {
  if (kind === 'focus') return 'focus'
  if (kind === 'arena1') return 'arena1'
  if (kind === 'arena2') return 'arena2'
  if (kind === 'arena3') return 'arena3'
  return kind
}

const TARGETING_COMMANDS: Record<string, string> = {
  'target:arena1': 'TARGETARENA1',
  'target:arena2': 'TARGETARENA2',
  'target:arena3': 'TARGETARENA3',
}

const SET_FOCUS_MACRO = '/focus [@mouseover,exists][]'

export function macroName(bind: ExportBind): string {
  const target = variantTarget(bind.ability.variantKind)
  const compactName = bind.name.replace(/[^\p{L}\p{N}]/gu, '').slice(0, 12)
  return `KO${target === 'base' ? '' : target[0]?.toUpperCase()}${target.slice(1, 3)}${compactName}`.slice(0, 16)
}

export function macroBody(bind: ExportBind): string | null {
  const kind = bind.ability.variantKind
  if (bind.ability.id === 'focus:set') return SET_FOCUS_MACRO
  if (bind.ability.category === 'targeting') return null
  if (kind === 'focus') return `#showtooltip ${bind.name}\n/cast [@focus,exists][] ${bind.name}`
  if (kind === 'arena1' || kind === 'arena2' || kind === 'arena3') {
    return `#showtooltip ${bind.name}\n/cast [@${kind}] ${bind.name}`
  }
  if (bind.ability.targeting === 'ally' && bind.ability.spellId > 0) {
    return `#showtooltip ${bind.name}\n/cast [@mouseover,help,nodead][help][@player] ${bind.name}`
  }
  if (bind.ability.id === 'trinket:1') return `/use 13`
  if (bind.ability.id === 'trinket:pvp') return `/use 14`
  return null
}

export function renderMacroList(binds: ExportBind[]): string {
  const sections: string[] = []
  for (const bind of binds) {
    const body = macroBody(bind)
    if (body === null) continue
    sections.push(`-- ${macroName(bind)} (${bind.wowKey})\n${body}`)
  }
  return sections.join('\n\n')
}

export interface LuaBindEntry {
  key: string
  spell?: number
  item?: number
  command?: string
  macrotext?: string
  name?: string
  target?: string
  mouseover?: boolean
  category?: string
  variant?: string
  slot?: number
}

export interface LuaBindPlacement {
  bind: ExportBind
  entry: LuaBindEntry
}

export function buildLuaBindPlacements(
  binds: ExportBind[],
  decor?: AddonDecor,
): LuaBindPlacement[] {
  const placements: LuaBindPlacement[] = []
  const entries: LuaBindEntry[] = []
  const planned: PlannedBind[] = []

  for (const bind of binds) {
    const entry: LuaBindEntry = { key: bind.wowKey }
    if (bind.ability.id === 'trinket:1') {
      entry.item = 13
      entry.name = bind.name
    } else if (bind.ability.id === 'trinket:pvp') {
      entry.item = 14
      entry.name = bind.name
    } else if (TARGETING_COMMANDS[bind.ability.id]) {
      entry.command = TARGETING_COMMANDS[bind.ability.id]
      entry.name = bind.name
    } else if (bind.ability.id === 'focus:set') {
      entry.macrotext = SET_FOCUS_MACRO
      entry.name = bind.name
    } else if (bind.ability.spellId > 0) {
      entry.spell = bind.ability.spellId
      if (bind.ability.variantKind === 'focus') entry.target = 'focus'
      else if (bind.ability.variantKind.startsWith('arena')) entry.target = bind.ability.variantKind
      else if (bind.ability.targeting === 'ally') entry.mouseover = true
    } else {
      continue
    }

    if (decor) {
      entry.category = bind.ability.category
      if (bind.ability.variantKind !== 'base' && bind.ability.category !== 'targeting') {
        entry.variant = variantTarget(bind.ability.variantKind)
      }
    }

    entries.push(entry)
    placements.push({ bind, entry })
    planned.push({
      keyId: bind.slot.keyId,
      modifier: bind.slot.modifier,
      placeable: entry.command === undefined,
    })
  }

  const plan = buildPlacementPlan(planned)
  entries.forEach((entry, index) => {
    const slot = plan[index]
    if (slot !== null && slot !== undefined) entry.slot = slot
  })
  return placements
}

export function buildLuaBindEntries(binds: ExportBind[], decor?: AddonDecor): LuaBindEntry[] {
  return buildLuaBindPlacements(binds, decor).map((placement) => placement.entry)
}

export interface AddonProfile {
  id: string
  name: string
  mode: GameMode
  specId: number
  classTag: string
  hash: string
  binds: LuaBindEntry[]
  keyboard: AddonKeyboardRow[]
}

function fnv1a(input: string): string {
  let hash = 0x811c9dc5
  for (let i = 0; i < input.length; i++) {
    hash ^= input.charCodeAt(i)
    hash = Math.imul(hash, 0x01000193) >>> 0
  }
  return hash.toString(16).padStart(8, '0')
}

export function buildAddonProfile(
  id: string,
  name: string,
  mode: GameMode,
  specId: number,
  classTag: string,
  binds: ExportBind[],
  keyboard: AddonKeyboardRow[],
  decor?: AddonDecor,
): AddonProfile {
  const entries = buildLuaBindEntries(binds, decor)
  const signature = entries
    .map(
      (entry) =>
        `${entry.key}|${entry.spell ?? ''}|${entry.item ?? ''}|${entry.command ?? ''}|${entry.macrotext ?? ''}|${entry.target ?? ''}|${entry.mouseover ? 1 : 0}|${entry.slot ?? ''}`,
    )
    .join(';')
  return {
    id,
    name,
    mode,
    specId,
    classTag,
    hash: fnv1a(`${specId}:${signature}`),
    binds: entries,
    keyboard,
  }
}

function luaBindLiteral(entry: LuaBindEntry): string {
  const parts = [`key = "${entry.key}"`]
  if (entry.spell !== undefined) parts.push(`spell = ${entry.spell}`)
  if (entry.item !== undefined) parts.push(`item = ${entry.item}`)
  if (entry.command !== undefined) parts.push(`command = "${entry.command}"`)
  if (entry.macrotext !== undefined) parts.push(`macrotext = "${escapeLua(entry.macrotext)}"`)
  if (entry.name !== undefined) parts.push(`name = "${escapeLua(entry.name)}"`)
  if (entry.target !== undefined) parts.push(`target = "${entry.target}"`)
  if (entry.mouseover) parts.push(`mouseover = true`)
  if (entry.category !== undefined) parts.push(`category = "${entry.category}"`)
  if (entry.variant !== undefined) parts.push(`variant = "${entry.variant}"`)
  if (entry.slot !== undefined) parts.push(`slot = ${entry.slot}`)
  return `      { ${parts.join(', ')} },`
}

function escapeLua(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
}

function buildLegendCategories(profiles: AddonProfile[]): string[] {
  const seen = new Set<string>()
  const categories: string[] = []
  for (const profile of profiles) {
    for (const entry of profile.binds) {
      if (!entry.category || seen.has(entry.category)) continue
      seen.add(entry.category)
      categories.push(entry.category)
    }
  }
  return categories
}

function localeStringsLiteral(strings: AddonLocaleStrings, colorKeys: string[]): string[] {
  const categoryLines = colorKeys.map(
    (key) => `      ["${key}"] = "${escapeLua(strings.categories[key as AbilityCategory] ?? key)}",`,
  )
  const uiLines = ADDON_UI_KEYS.map(
    (key) => `      ${key} = "${escapeLua(strings.ui[key])}",`,
  )
  return [`    categories = {`, ...categoryLines, `    },`, `    ui = {`, ...uiLines, `    },`]
}

export const DEFAULT_ADDON_UI: Record<AddonUiKey, string> = {
  optionsTitle: 'Keybind Optimizer',
  colorsLabel: 'Category colors',
  colorsTooltip: 'Color action buttons by ability category.',
  legendLabel: 'Color legend',
  legendTooltip: 'Show the draggable color legend.',
  mainbarLabel: 'Use the main action bar',
  mainbarTooltip: 'Place abilities on the main bar (slots 1-12) too.',
  autoApplyLabel: 'Apply layout on login',
  autoApplyTooltip: 'Re-apply automatically after login or /reload, only if the bars drifted.',
  mouseoverLabel: 'Mouseover macros for ally spells',
  mouseoverTooltip: 'Cast ally-targeted spells on the unit under the cursor.',
  openBrowser: 'Layout browser…',
  applyNow: 'Apply now',
  browserTitle: 'Keybind Optimizer — layouts',
  profilesHeader: 'Layouts',
  applyButton: 'Apply',
  appliedTag: 'applied',
  activeTag: 'selected',
  keysOnlyHeader: 'Key-only binds (not on bars)',
  unknownTag: 'not known by this character',
  specMismatch: 'This layout was built for another specialization',
  msgApplied: '%d keys bound, %d abilities placed',
  msgBoundOnly: 'bound to keys but not placed on bars: %s',
  msgSkipped: 'skipped (not known by this character): %s',
  msgIntact: 'layout already applied — nothing to do',
  msgCombat: 'in combat — will apply after combat ends',
  msgSpecSkip: 'layout is for another spec — /kbo force to apply anyway',
  enableBarsHint: 'some abilities are on hidden bars — type /kbo bars, or enable them in Edit Mode',
  msgBarsEnabled: 'action bars enabled — /reload if any are still hidden',
  msgBarsManual: 'could not toggle bars automatically — enable them in Edit Mode (HUD)',
  msgCleared: 'main action bar spells cleared (mounts, toys and macros kept)',
  msgProfile: 'layout selected: %s',
  msgCheckOk: 'layout matches the bars and bindings',
  msgCheckDrift: 'layout drift detected — run /kbo apply',
  msgAuto: 'auto-apply on login: %s',
  msgMouseover: 'mouseover macros: %s — run /kbo apply',
  msgColors: 'category colors: %s',
  msgLegend: 'legend: %s',
  msgMainbar: 'main bar usage: %s — run /kbo apply',
  msgSpecAdapted: 'no exact layout for this spec — applied the class-wide binds; generate a full one on the site',
  msgSpecSwitched: 'spec changed — applying: %s',
  msgAccountBinds: 'note: your key bindings are account-wide — enable character-specific bindings if your other characters use different layouts',
  viewKeyboard: 'Keyboard',
  viewBars: 'Action bars',
  layerBase: 'Base',
  historyHeader: 'History',
  backupSave: 'Save current layout',
  backupAuto: 'auto-backup',
  backupManual: 'saved manually',
  restoreButton: 'Restore',
  msgBackupSaved: 'current layout saved: %s',
  msgRestored: 'layout restored: %s',
  forceButton: 'Force apply',
  checkButton: 'Verify layout',
  barsButton: 'Show hidden bars',
  clearMainButton: 'Clear main bar',
  importButton: 'Import layout…',
  importTitle: 'Import a layout from the site',
  importHint: 'Paste the import string (starts with !KBO1!) and press Import — no addon re-download needed.',
  importAccept: 'Import',
  importCancel: 'Cancel',
  importedTag: 'imported',
  msgImported: 'layouts imported: %d — select one and press Apply',
  importErrFormat: 'import string is corrupted or has an unsupported format',
  importErrChecksum: 'import string is incomplete — copy it fully and paste again',
  importErrClient: 'this game client does not support import strings (C_EncodingUtil missing)',
  stateOn: 'ON',
  stateOff: 'OFF',
  help: '/kbo — layout browser, /kbo apply — apply, /kbo force — force apply, /kbo check — verify, /kbo import — import a layout string, /kbo profile N — pick layout, /kbo bars — show hidden bars, /kbo auto — login auto-apply, /kbo colors, /kbo legend, /kbo mainbar, /kbo mouseover, /kbo clearmain',
}

const DEFAULT_LOCALE_STRINGS = (categories: Record<string, string>): AddonLocaleStrings => ({
  categories: categories as Record<AbilityCategory, string>,
  ui: { ...DEFAULT_ADDON_UI },
})

function keyboardRowLiteral(row: AddonKeyboardRow): string {
  const keys = row.map((key) => {
    const parts = [`k = "${escapeLua(key.k)}"`, `label = "${escapeLua(key.label)}"`, `x = ${key.x}`, `w = ${key.w}`]
    if (key.m) parts.push(`m = true`)
    return `{ ${parts.join(', ')} }`
  })
  return `    { ${keys.join(', ')} },`
}

export function renderLuaAddon(
  profiles: AddonProfile[],
  addonName: string,
  decor?: AddonDecor,
): string {
  const legendCategories = decor ? buildLegendCategories(profiles) : []
  const colorKeys = Object.keys(decor?.colorByCategory ?? {})
  const ru = decor?.ru ?? DEFAULT_LOCALE_STRINGS({})
  const en = decor?.en ?? DEFAULT_LOCALE_STRINGS({})
  const keyboardIndexBySignature = new Map<string, number>()
  const keyboards: AddonKeyboardRow[][] = []
  const keyboardIndexFor = (keyboard: AddonKeyboardRow[]): number => {
    const signature = JSON.stringify(keyboard)
    const existing = keyboardIndexBySignature.get(signature)
    if (existing !== undefined) return existing
    keyboards.push(keyboard)
    keyboardIndexBySignature.set(signature, keyboards.length)
    return keyboards.length
  }
  const profileBlocks = profiles.flatMap((profile) => [
    `  {`,
    `    id = "${escapeLua(profile.id)}",`,
    `    name = "${escapeLua(profile.name)}",`,
    `    mode = "${profile.mode}",`,
    `    spec = ${profile.specId},`,
    `    class = "${escapeLua(profile.classTag)}",`,
    `    hash = "${profile.hash}",`,
    `    kb = ${keyboardIndexFor(profile.keyboard)},`,
    `    binds = {`,
    ...profile.binds.map(luaBindLiteral),
    `    },`,
    `  },`,
  ])
  const keyboardBlocks = keyboards.flatMap((keyboard) => [
    `  {`,
    ...keyboard.map(keyboardRowLiteral),
    `  },`,
  ])
  return [
    `local ADDON = "${addonName}"`,
    `local COLORS = {`,
    ...colorKeys.map((key) => `  ["${key}"] = "${decor?.colorByCategory[key as AbilityCategory]}",`),
    `}`,
    `local STRINGS = {`,
    `  ru = {`,
    ...localeStringsLiteral(ru, colorKeys),
    `  },`,
    `  en = {`,
    ...localeStringsLiteral(en, colorKeys),
    `  },`,
    `}`,
    `local LOCALE = (GetLocale and string.sub(GetLocale(), 1, 2) == "ru") and "ru" or "en"`,
    `local L = STRINGS[LOCALE]`,
    `local UI = L.ui`,
    ``,
    `local PROFILES = {`,
    ...profileBlocks,
    `}`,
    ``,
    `local KEYBOARDS = {`,
    ...keyboardBlocks,
    `}`,
    ``,
    `local LEGEND_CATEGORIES = { ${legendCategories.map((c) => `"${c}"`).join(', ')} }`,
    ``,
    `local BAR_SIZE = ${BAR_SIZE}`,
    `local BARS = {`,
    `  { base = 0, command = "ACTIONBUTTON", frame = "ActionButton", main = true },`,
    `  { base = 60, command = "MULTIACTIONBAR1BUTTON", frame = "MultiBarBottomLeftButton", toggle = 1, editIndex = 2 },`,
    `  { base = 48, command = "MULTIACTIONBAR2BUTTON", frame = "MultiBarBottomRightButton", toggle = 2, editIndex = 3 },`,
    `  { base = 24, command = "MULTIACTIONBAR3BUTTON", frame = "MultiBarRightButton", toggle = 3, editIndex = 4 },`,
    `  { base = 36, command = "MULTIACTIONBAR4BUTTON", frame = "MultiBarLeftButton", toggle = 4, editIndex = 5 },`,
    `  { base = 144, command = "MULTIACTIONBAR5BUTTON", frame = "MultiBar5Button", editIndex = 6 },`,
    `  { base = 156, command = "MULTIACTIONBAR6BUTTON", frame = "MultiBar6Button", editIndex = 7 },`,
    `  { base = 168, command = "MULTIACTIONBAR7BUTTON", frame = "MultiBar7Button", editIndex = 8 },`,
    `}`,
    ``,
    `local QUESTION_ICON = 134400`,
    ``,
    `local function printMsg(text)`,
    `  print("|cff7c78ff" .. ADDON .. "|r: " .. text)`,
    `end`,
    ``,
    `local function stateText(value)`,
    `  return value and UI.stateOn or UI.stateOff`,
    `end`,
    ``,
    `local function hexColor(hex)`,
    `  return tonumber(string.sub(hex, 1, 2), 16) / 255, tonumber(string.sub(hex, 3, 4), 16) / 255, tonumber(string.sub(hex, 5, 6), 16) / 255`,
    `end`,
    ``,
    `local decoratedButtons = {}`,
    ``,
    `local function db()`,
    `  KeybindOptimizerDB = KeybindOptimizerDB or {}`,
    `  local d = KeybindOptimizerDB`,
    `  if d.decor == nil then d.decor = true end`,
    `  if d.legend == nil then d.legend = true end`,
    `  if d.mainbar == nil then d.mainbar = true end`,
    `  if d.autoApply == nil then d.autoApply = true end`,
    `  if d.mouseover == nil then d.mouseover = true end`,
    `  if d.imported == nil then d.imported = {} end`,
    `  return d`,
    `end`,
    ``,
    `local function chardb()`,
    `  KeybindOptimizerCharDB = KeybindOptimizerCharDB or {}`,
    `  local c = KeybindOptimizerCharDB`,
    `  c.profileBySpec = c.profileBySpec or {}`,
    `  c.appliedBySpec = c.appliedBySpec or {}`,
    `  c.backups = c.backups or {}`,
    `  return c`,
    `end`,
    ``,
    `local function currentSpecId()`,
    `  if GetSpecialization and GetSpecializationInfo then`,
    `    local index = GetSpecialization()`,
    `    if index then`,
    `      return (GetSpecializationInfo(index))`,
    `    end`,
    `  end`,
    `  return nil`,
    `end`,
    ``,
    `local function specKey()`,
    `  return currentSpecId() or 0`,
    `end`,
    ``,
    `local function specState()`,
    `  local c = chardb()`,
    `  local key = specKey()`,
    `  c.appliedBySpec[key] = c.appliedBySpec[key] or {}`,
    `  return c.appliedBySpec[key]`,
    `end`,
    ``,
    `local function invalidateApplied()`,
    `  for _, state in pairs(chardb().appliedBySpec) do`,
    `    state.hash = nil`,
    `  end`,
    `end`,
    ``,
    `local function playerClassTag()`,
    `  local _, classTag = UnitClass("player")`,
    `  return classTag`,
    `end`,
    ``,
    `local function importedProfiles()`,
    `  return db().imported`,
    `end`,
    ``,
    `local function allProfiles()`,
    `  local list = {}`,
    `  for _, profile in ipairs(PROFILES) do`,
    `    table.insert(list, profile)`,
    `  end`,
    `  for _, profile in ipairs(importedProfiles()) do`,
    `    table.insert(list, profile)`,
    `  end`,
    `  return list`,
    `end`,
    ``,
    `local function currentProfileIndex()`,
    `  local profiles = allProfiles()`,
    `  local c = chardb()`,
    `  local key = specKey()`,
    `  local chosen = c.profileBySpec[key]`,
    `  if type(chosen) == "number" and PROFILES[chosen] then return chosen end`,
    `  if type(chosen) == "string" then`,
    `    for index, profile in ipairs(profiles) do`,
    `      if profile.id == chosen then return index end`,
    `    end`,
    `  end`,
    `  for index, profile in ipairs(profiles) do`,
    `    if profile.spec == key then return index end`,
    `  end`,
    `  local classTag = playerClassTag()`,
    `  for index, profile in ipairs(profiles) do`,
    `    if profile.class == classTag then return index end`,
    `  end`,
    `  return 1`,
    `end`,
    ``,
    `local function currentProfile()`,
    `  local profiles = allProfiles()`,
    `  return profiles[currentProfileIndex()] or profiles[1]`,
    `end`,
    ``,
    `local function specMatches(profile)`,
    `  local specId = currentSpecId()`,
    `  return specId == nil or profile.spec == nil or profile.spec == 0 or specId == profile.spec`,
    `end`,
    ``,
    `local function classMatches(profile)`,
    `  return profile.class == nil or profile.class == "" or profile.class == playerClassTag()`,
    `end`,
    ``,
    `local function mainBarPages()`,
    `  local _, class = UnitClass("player")`,
    `  return class == "DRUID" or class == "ROGUE"`,
    `end`,
    ``,
    `local function usableBars()`,
    `  local bars = {}`,
    `  local useMain = db().mainbar and not mainBarPages()`,
    `  for _, bar in ipairs(BARS) do`,
    `    if not bar.main or useMain then`,
    `      table.insert(bars, bar)`,
    `    end`,
    `  end`,
    `  return bars`,
    `end`,
    ``,
    `local function isOwnedMacroName(name)`,
    `  return name and string.match(name, "^KO%d+$") ~= nil`,
    `end`,
    ``,
    `local function buildTargets()`,
    `  local targets = {}`,
    `  for _, bar in ipairs(usableBars()) do`,
    `    for i = 1, BAR_SIZE do`,
    `      table.insert(targets, { slot = bar.base + i, command = bar.command .. i, frame = _G[bar.frame .. i], toggle = bar.toggle })`,
    `    end`,
    `  end`,
    `  return targets`,
    `end`,
    ``,
    `local function isProtectedSlot(slot)`,
    `  local actionType, id = GetActionInfo(slot)`,
    `  if not actionType then return false end`,
    `  if actionType == "spell" then return false end`,
    `  if actionType == "macro" then`,
    `    local name = GetMacroInfo(id)`,
    `    return not isOwnedMacroName(name)`,
    `  end`,
    `  return true`,
    `end`,
    ``,
    `local function clearOwnedButtons()`,
    `  for slot = 1, 180 do`,
    `    local actionType, id = GetActionInfo(slot)`,
    `    if actionType == "macro" then`,
    `      local name = GetMacroInfo(id)`,
    `      if isOwnedMacroName(name) then`,
    `        PickupAction(slot)`,
    `        ClearCursor()`,
    `      end`,
    `    end`,
    `  end`,
    `end`,
    ``,
    `local function actionButtonNameRegion(button)`,
    `  if not button then return nil end`,
    `  if button.Name then return button.Name end`,
    `  local frameName = button.GetName and button:GetName()`,
    `  if frameName then return _G[frameName .. "Name"] end`,
    `  return nil`,
    `end`,
    ``,
    `local function refreshMacroNameVisibility(slot, button)`,
    `  local region = actionButtonNameRegion(button)`,
    `  if not region then return end`,
    `  local actionType, id = GetActionInfo(slot)`,
    `  local hide = actionType == "macro" and isOwnedMacroName((GetMacroInfo(id)))`,
    `  region:SetAlpha(hide and 0 or 1)`,
    `end`,
    ``,
    `local function refreshAllMacroNames()`,
    `  for _, bar in ipairs(BARS) do`,
    `    for i = 1, BAR_SIZE do`,
    `      refreshMacroNameVisibility(bar.base + i, _G[bar.frame .. i])`,
    `    end`,
    `  end`,
    `end`,
    ``,
    `local macroNameRefreshPending = false`,
    `local function scheduleMacroNameRefresh()`,
    `  if macroNameRefreshPending then return end`,
    `  macroNameRefreshPending = true`,
    `  C_Timer.After(0.2, function()`,
    `    macroNameRefreshPending = false`,
    `    refreshAllMacroNames()`,
    `  end)`,
    `end`,
    ``,
    `local function adler32Hex(text)`,
    `  local low = 1`,
    `  local high = 0`,
    `  for i = 1, #text do`,
    `    low = (low + string.byte(text, i)) % 65521`,
    `    high = (high + low) % 65521`,
    `  end`,
    `  return string.format("%04x%04x", high, low)`,
    `end`,
    ``,
    `local function decodeImportPayload(encoded)`,
    `  if not (C_EncodingUtil and C_EncodingUtil.DecodeBase64 and C_EncodingUtil.DecompressString and C_EncodingUtil.DeserializeJSON) then`,
    `    return nil, UI.importErrClient`,
    `  end`,
    `  local okDecode, compressed = pcall(C_EncodingUtil.DecodeBase64, encoded)`,
    `  if not okDecode or type(compressed) ~= "string" then return nil, UI.importErrFormat end`,
    `  local okInflate, json = pcall(C_EncodingUtil.DecompressString, compressed, Enum.CompressionMethod and Enum.CompressionMethod.Zlib or 2)`,
    `  if not okInflate or type(json) ~= "string" then return nil, UI.importErrFormat end`,
    `  local okParse, payload = pcall(C_EncodingUtil.DeserializeJSON, json)`,
    `  if not okParse then return nil, UI.importErrFormat end`,
    `  return payload`,
    `end`,
    ``,
    `local function importFromString(text)`,
    `  local compact = string.gsub(text or "", "%s+", "")`,
    `  local encoded, checksum = string.match(compact, "^!KBO1!([A-Za-z0-9+/=]+)!(%x+)!$")`,
    `  if not encoded or not checksum then return nil, UI.importErrFormat end`,
    `  if adler32Hex(encoded) ~= string.lower(checksum) then return nil, UI.importErrChecksum end`,
    `  local payload, decodeErr = decodeImportPayload(encoded)`,
    `  if not payload then return nil, decodeErr end`,
    `  if type(payload) ~= "table" or payload.v ~= 1 or type(payload.profiles) ~= "table" then`,
    `    return nil, UI.importErrFormat`,
    `  end`,
    `  local keyboards = type(payload.keyboards) == "table" and payload.keyboards or {}`,
    `  local imported = importedProfiles()`,
    `  local count = 0`,
    `  for _, raw in ipairs(payload.profiles) do`,
    `    if type(raw) == "table" and type(raw.id) == "string" and type(raw.binds) == "table" then`,
    `      local profile = {`,
    `        id = raw.id,`,
    `        name = tostring(raw.name or raw.id),`,
    `        mode = raw.mode,`,
    `        spec = tonumber(raw.spec) or 0,`,
    `        class = tostring(raw.class or ""),`,
    `        hash = tostring(raw.hash or ""),`,
    `        keyboard = keyboards[raw.kb],`,
    `        imported = true,`,
    `        binds = {},`,
    `      }`,
    `      for _, bind in ipairs(raw.binds) do`,
    `        if type(bind) == "table" and type(bind.key) == "string" then`,
    `          table.insert(profile.binds, bind)`,
    `        end`,
    `      end`,
    `      if #profile.binds > 0 then`,
    `        for index = #imported, 1, -1 do`,
    `          if imported[index].id == profile.id then table.remove(imported, index) end`,
    `        end`,
    `        table.insert(imported, profile)`,
    `        count = count + 1`,
    `      end`,
    `    end`,
    `  end`,
    `  while #imported > 10 do`,
    `    table.remove(imported, 1)`,
    `  end`,
    `  if count == 0 then return nil, UI.importErrFormat end`,
    `  return count`,
    `end`,
    ``,
    `local function noteFor(category, variant)`,
    `  local label = L.categories[category] or category`,
    `  if variant and variant ~= "" then`,
    `    return label .. " [@" .. variant .. "]"`,
    `  end`,
    `  return label`,
    `end`,
    ``,
    `local function decorateButton(button, category, variant)`,
    `  if not button or not category then return end`,
    `  local color = COLORS[category]`,
    `  if not color then return end`,
    `  local note = noteFor(category, variant)`,
    `  local r, g, b = hexColor(color)`,
    `  local bar = button.koCategoryBar`,
    `  if not bar then`,
    `    bar = button:CreateTexture(nil, "OVERLAY", nil, 7)`,
    `    button.koCategoryBar = bar`,
    `  end`,
    `  bar:ClearAllPoints()`,
    `  bar:SetPoint("BOTTOMLEFT", button, "BOTTOMLEFT", 1, 1)`,
    `  bar:SetPoint("BOTTOMRIGHT", button, "BOTTOMRIGHT", -1, 1)`,
    `  bar:SetHeight(5)`,
    `  bar:SetColorTexture(r, g, b, 1)`,
    `  bar:SetShown(db().decor)`,
    `  button.koNote = note`,
    `  button.koR, button.koG, button.koB = r, g, b`,
    `  decoratedButtons[button] = true`,
    `  if not button.koHooked then`,
    `    button.koHooked = true`,
    `    button:HookScript("OnEnter", function(self)`,
    `      if self.koNote and db().decor then`,
    `        GameTooltip:AddLine(self.koNote, self.koR, self.koG, self.koB)`,
    `        GameTooltip:Show()`,
    `      end`,
    `    end)`,
    `  end`,
    `end`,
    ``,
    `local function setDecorShown(shown)`,
    `  for button in pairs(decoratedButtons) do`,
    `    if button.koCategoryBar then`,
    `      button.koCategoryBar:SetShown(shown)`,
    `    end`,
    `  end`,
    `end`,
    ``,
    `local updateLegend`,
    `local updateBrowser`,
    `local optChecks = {}`,
    `local function syncOptions()`,
    `  for key, check in pairs(optChecks) do`,
    `    check:SetChecked(db()[key] and true or false)`,
    `  end`,
    `end`,
    ``,
    `local legendFrame = nil`,
    ``,
    `local function buildLegendFrame()`,
    `  if legendFrame then return legendFrame end`,
    `  local frame = CreateFrame("Frame", "KeybindOptimizerLegend", UIParent, "BackdropTemplate")`,
    `  frame:SetSize(200, 34 + #LEGEND_CATEGORIES * 18)`,
    `  frame:SetPoint("RIGHT", UIParent, "RIGHT", -220, 0)`,
    `  frame:SetBackdrop({ bgFile = "Interface/Tooltips/UI-Tooltip-Background", edgeFile = "Interface/Tooltips/UI-Tooltip-Border", edgeSize = 12, insets = { left = 3, right = 3, top = 3, bottom = 3 } })`,
    `  frame:SetBackdropColor(0.06, 0.06, 0.08, 0.92)`,
    `  frame:SetMovable(true)`,
    `  frame:EnableMouse(true)`,
    `  frame:RegisterForDrag("LeftButton")`,
    `  frame:SetScript("OnDragStart", frame.StartMoving)`,
    `  frame:SetScript("OnDragStop", frame.StopMovingOrSizing)`,
    `  frame:SetClampedToScreen(true)`,
    `  local title = frame:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")`,
    `  title:SetPoint("TOPLEFT", 10, -8)`,
    `  title:SetText(ADDON)`,
    `  local close = CreateFrame("Button", nil, frame, "UIPanelCloseButton")`,
    `  close:SetSize(24, 24)`,
    `  close:SetPoint("TOPRIGHT", 2, 2)`,
    `  close:SetScript("OnClick", function()`,
    `    db().legend = false`,
    `    updateLegend()`,
    `    syncOptions()`,
    `  end)`,
    `  for index, category in ipairs(LEGEND_CATEGORIES) do`,
    `    local swatch = frame:CreateTexture(nil, "OVERLAY")`,
    `    swatch:SetSize(10, 10)`,
    `    swatch:SetPoint("TOPLEFT", 10, -10 - index * 18)`,
    `    local r, g, b = hexColor(COLORS[category] or "888888")`,
    `    swatch:SetColorTexture(r, g, b, 1)`,
    `    local text = frame:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")`,
    `    text:SetPoint("LEFT", swatch, "RIGHT", 6, 0)`,
    `    text:SetText(L.categories[category] or category)`,
    `  end`,
    `  legendFrame = frame`,
    `  return frame`,
    `end`,
    ``,
    `updateLegend = function()`,
    `  if #LEGEND_CATEGORIES == 0 then return end`,
    `  local frame = buildLegendFrame()`,
    `  frame:SetShown(db().legend and db().decor)`,
    `end`,
    ``,
    `local function resolveSpellName(spellId)`,
    `  if C_Spell and C_Spell.GetSpellName then`,
    `    return C_Spell.GetSpellName(spellId)`,
    `  end`,
    `  if C_Spell and C_Spell.GetSpellInfo then`,
    `    local info = C_Spell.GetSpellInfo(spellId)`,
    `    if info then return info.name end`,
    `  end`,
    `  if GetSpellInfo then`,
    `    return (GetSpellInfo(spellId))`,
    `  end`,
    `  return nil`,
    `end`,
    ``,
    `local function spellOverride(spellId)`,
    `  if C_Spell and C_Spell.GetOverrideSpell then`,
    `    local override = C_Spell.GetOverrideSpell(spellId)`,
    `    if override and override > 0 then return override end`,
    `  end`,
    `  if FindSpellOverrideByID then`,
    `    local override = FindSpellOverrideByID(spellId)`,
    `    if override and override > 0 then return override end`,
    `  end`,
    `  return spellId`,
    `end`,
    ``,
    `local function actionMatchesSpell(actionId, spellId)`,
    `  if actionId == spellId then return true end`,
    `  if spellOverride(spellId) == actionId then return true end`,
    `  return spellOverride(actionId) == spellId`,
    `end`,
    ``,
    `local function cursorHasSpell(spellId)`,
    `  local kind, _, _, cursorSpellId, baseSpellId = GetCursorInfo()`,
    `  if kind ~= "spell" then return false end`,
    `  if cursorSpellId == spellId or baseSpellId == spellId then return true end`,
    `  if cursorSpellId and actionMatchesSpell(cursorSpellId, spellId) then return true end`,
    `  return false`,
    `end`,
    ``,
    `local function pickupSpell(spellId, name)`,
    `  ClearCursor()`,
    `  if C_Spell and C_Spell.PickupSpell then`,
    `    pcall(C_Spell.PickupSpell, spellId)`,
    `    if cursorHasSpell(spellId) then return true end`,
    `    ClearCursor()`,
    `  end`,
    `  if C_SpellBook and C_SpellBook.FindSpellBookSlotForSpell and C_SpellBook.PickupSpellBookItem then`,
    `    local ok, slotIndex, bank = pcall(C_SpellBook.FindSpellBookSlotForSpell, spellId)`,
    `    if ok and slotIndex then`,
    `      pcall(C_SpellBook.PickupSpellBookItem, slotIndex, bank or 0)`,
    `      if cursorHasSpell(spellId) then return true end`,
    `      ClearCursor()`,
    `    end`,
    `  end`,
    `  if PickupSpell then`,
    `    pcall(PickupSpell, spellId)`,
    `    if cursorHasSpell(spellId) then return true end`,
    `    ClearCursor()`,
    `    if name then`,
    `      pcall(PickupSpell, name)`,
    `      if cursorHasSpell(spellId) then return true end`,
    `      ClearCursor()`,
    `    end`,
    `  end`,
    `  return false`,
    `end`,
    ``,
    `local function knowsSpell(spellId)`,
    `  if C_SpellBook and C_SpellBook.IsSpellKnownOrOverridesKnown then`,
    `    return C_SpellBook.IsSpellKnownOrOverridesKnown(spellId)`,
    `  end`,
    `  if IsSpellKnownOrOverridesKnown then`,
    `    return IsSpellKnownOrOverridesKnown(spellId)`,
    `  end`,
    `  if C_SpellBook and C_SpellBook.IsSpellKnown then`,
    `    return C_SpellBook.IsSpellKnown(spellId)`,
    `  end`,
    `  if IsPlayerSpell then`,
    `    return IsPlayerSpell(spellId)`,
    `  end`,
    `  return true`,
    `end`,
    ``,
    `local function bindIsKnown(bind)`,
    `  if bind.spell then`,
    `    return resolveSpellName(bind.spell) ~= nil and knowsSpell(bind.spell)`,
    `  end`,
    `  if bind.item then`,
    `    return GetInventoryItemID("player", bind.item) ~= nil`,
    `  end`,
    `  return true`,
    `end`,
    ``,
    `local function macroLimits()`,
    `  local account = MAX_ACCOUNT_MACROS or 120`,
    `  local character = MAX_CHARACTER_MACROS or 18`,
    `  return account, character`,
    `end`,
    ``,
    `local function makeMacro(label, body)`,
    `  if GetMacroInfo(label) then`,
    `    EditMacro(label, label, 134400, body)`,
    `    return true`,
    `  end`,
    `  local maxAccount, maxCharacter = macroLimits()`,
    `  local accountCount, characterCount = GetNumMacros()`,
    `  if characterCount < maxCharacter then`,
    `    CreateMacro(label, 134400, body, true)`,
    `  elseif accountCount < maxAccount then`,
    `    CreateMacro(label, 134400, body, false)`,
    `  end`,
    `  return GetMacroInfo(label) ~= nil`,
    `end`,
    ``,
    `local function buildMacroBody(bind, name)`,
    `  if bind.macrotext then`,
    `    return bind.macrotext`,
    `  end`,
    `  if bind.item then`,
    `    return "#showtooltip\\n/use " .. bind.item`,
    `  end`,
    `  if not name then return nil end`,
    `  if bind.target == "focus" then`,
    `    return "#showtooltip " .. name .. "\\n/cast [@focus,exists][] " .. name`,
    `  end`,
    `  if bind.target then`,
    `    return "#showtooltip " .. name .. "\\n/cast [@" .. bind.target .. "] " .. name`,
    `  end`,
    `  if bind.mouseover and db().mouseover then`,
    `    return "#showtooltip " .. name .. "\\n/cast [@mouseover,help,nodead][help][@player] " .. name`,
    `  end`,
    `  return nil`,
    `end`,
    ``,
    `local function buildSpellMacroBody(name)`,
    `  return "#showtooltip " .. name .. "\\n/cast " .. name`,
    `end`,
    ``,
    `local function bindKeyToCommand(key, command)`,
    `  local first, second = GetBindingKey(command)`,
    `  if first and first ~= key then SetBinding(first) end`,
    `  if second and second ~= key then SetBinding(second) end`,
    `  SetBinding(key, command)`,
    `  return GetBindingAction(key) == command`,
    `end`,
    ``,
    `local function placeVerified(slot, label, spellId)`,
    `  PlaceAction(slot)`,
    `  ClearCursor()`,
    `  local actionType, id = GetActionInfo(slot)`,
    `  if label then`,
    `    if actionType ~= "macro" then return false end`,
    `    return GetMacroInfo(id) == label`,
    `  end`,
    `  if spellId then`,
    `    return actionType == "spell" and actionMatchesSpell(id, spellId)`,
    `  end`,
    `  return HasAction(slot)`,
    `end`,
    ``,
    `local function placeMacro(label, target)`,
    `  ClearCursor()`,
    `  PickupMacro(label)`,
    `  if GetCursorInfo() == nil then return false end`,
    `  return placeVerified(target.slot, label)`,
    `end`,
    ``,
    `local function captureBackup(label, isAuto)`,
    `  local c = chardb()`,
    `  local snapshot = { name = label, at = date("%d.%m %H:%M"), auto = isAuto or nil, slots = {}, macros = {}, macroBodies = {}, binds = {} }`,
    `  for _, bar in ipairs(BARS) do`,
    `    for i = 1, BAR_SIZE do`,
    `      local slot = bar.base + i`,
    `      local actionType, id = GetActionInfo(slot)`,
    `      if actionType == "spell" and id and id > 0 then`,
    `        snapshot.slots[slot] = id`,
    `      elseif actionType == "macro" then`,
    `        local macroName, _, macroBody = GetMacroInfo(id)`,
    `        if isOwnedMacroName(macroName) then`,
    `          snapshot.macros[slot] = macroName`,
    `          snapshot.macroBodies[macroName] = macroBody`,
    `        end`,
    `      end`,
    `    end`,
    `  end`,
    `  local seenKeys = {}`,
    `  for _, profile in ipairs(allProfiles()) do`,
    `    for _, bind in ipairs(profile.binds) do`,
    `      if not seenKeys[bind.key] then`,
    `        seenKeys[bind.key] = true`,
    `        local action = GetBindingAction(bind.key) or ""`,
    `        snapshot.binds[bind.key] = action`,
    `        local macroLabel = string.match(action, "^MACRO (KO%d+)$")`,
    `        if macroLabel and not snapshot.macroBodies[macroLabel] then`,
    `          local macroName, _, macroBody = GetMacroInfo(macroLabel)`,
    `          if macroName then snapshot.macroBodies[macroLabel] = macroBody end`,
    `        end`,
    `      end`,
    `    end`,
    `  end`,
    `  table.insert(c.backups, snapshot)`,
    `  local function countBackups(auto)`,
    `    local total = 0`,
    `    for _, backup in ipairs(c.backups) do`,
    `      if (backup.auto and true or false) == auto then total = total + 1 end`,
    `    end`,
    `    return total`,
    `  end`,
    `  local function removeOldest(auto)`,
    `    for backupIndex, backup in ipairs(c.backups) do`,
    `      if (backup.auto and true or false) == auto then`,
    `        table.remove(c.backups, backupIndex)`,
    `        return`,
    `      end`,
    `    end`,
    `  end`,
    `  while countBackups(true) > 2 do removeOldest(true) end`,
    `  while countBackups(false) > 5 do removeOldest(false) end`,
    `  return snapshot`,
    `end`,
    ``,
    `local applyQueued = nil`,
    ``,
    `local function profileSpellSet(profile)`,
    `  local set = {}`,
    `  for _, bind in ipairs(profile.binds) do`,
    `    if bind.spell then`,
    `      set[bind.spell] = true`,
    `      set[spellOverride(bind.spell)] = true`,
    `    end`,
    `  end`,
    `  return set`,
    `end`,
    ``,
    `local function claimedSlotSet(st)`,
    `  local set = {}`,
    `  for _, record in pairs(st.placements or {}) do`,
    `    if record.slot then set[record.slot] = true end`,
    `  end`,
    `  return set`,
    `end`,
    ``,
    `local function hasStrayActions(profile, st)`,
    `  local wanted = claimedSlotSet(st)`,
    `  local spells = profileSpellSet(profile)`,
    `  for _, target in ipairs(buildTargets()) do`,
    `    if not wanted[target.slot] then`,
    `      local actionType, id = GetActionInfo(target.slot)`,
    `      if actionType == "macro" then`,
    `        if isOwnedMacroName((GetMacroInfo(id))) then return true end`,
    `      elseif actionType == "spell" and id then`,
    `        if spells[id] or spells[spellOverride(id)] then return true end`,
    `      end`,
    `    end`,
    `  end`,
    `  return false`,
    `end`,
    ``,
    `local function verifyApplied(profile)`,
    `  local st = specState()`,
    `  if st.hash ~= profile.hash then return false end`,
    `  st.placements = st.placements or {}`,
    `  for index, bind in ipairs(profile.binds) do`,
    `    local record = st.placements[index]`,
    `    if bindIsKnown(bind) then`,
    `      if not record then return false end`,
    `      if record.action and (GetBindingAction(bind.key) or "") ~= record.action then return false end`,
    `      if record.slot then`,
    `        local actionType, id = GetActionInfo(record.slot)`,
    `        if record.macro then`,
    `          if actionType ~= "macro" or GetMacroInfo(id) ~= record.macro then return false end`,
    `        elseif record.spell then`,
    `          if actionType ~= "spell" or not actionMatchesSpell(id, record.spell) then return false end`,
    `        end`,
    `      end`,
    `    end`,
    `  end`,
    `  if hasStrayActions(profile, st) then return false end`,
    `  return true`,
    `end`,
    ``,
    `local function plannedTargetIndex(bind, barCount)`,
    `  if bind.slot == nil then return nil end`,
    `  local barIndex = math.floor(bind.slot / BAR_SIZE)`,
    `  if barIndex >= barCount then return nil end`,
    `  return barIndex * BAR_SIZE + (bind.slot % BAR_SIZE) + 1`,
    `end`,
    ``,
    `local lastUsedToggles = {}`,
    ``,
    `local function apply(mode)`,
    `  mode = mode or "manual"`,
    `  local profile = currentProfile()`,
    `  if not profile then return end`,
    `  if InCombatLockdown() then`,
    `    applyQueued = mode`,
    `    printMsg(UI.msgCombat)`,
    `    return`,
    `  end`,
    `  local st = specState()`,
    `  if not classMatches(profile) and mode ~= "force" then`,
    `    if mode == "manual" then printMsg(UI.msgSpecSkip) end`,
    `    return`,
    `  end`,
    `  local adapted = not specMatches(profile)`,
    `  if adapted and mode == "auto" then return end`,
    `  if mode ~= "force" and verifyApplied(profile) then`,
    `    if mode == "manual" then printMsg(UI.msgIntact) end`,
    `    updateLegend()`,
    `    return`,
    `  end`,
    `  captureBackup(UI.backupAuto, true)`,
    `  clearOwnedButtons()`,
    `  for _, record in pairs(st.placements or {}) do`,
    `    if record.slot and HasAction(record.slot) and not isProtectedSlot(record.slot) then`,
    `      PickupAction(record.slot)`,
    `      ClearCursor()`,
    `    end`,
    `  end`,
    `  local targets = buildTargets()`,
    `  local barCount = math.floor(#targets / BAR_SIZE)`,
    `  local claimed = {}`,
    `  for index, bind in ipairs(profile.binds) do`,
    `    if not bind.command and bindIsKnown(bind) then`,
    `      local ti = plannedTargetIndex(bind, barCount)`,
    `      if ti and targets[ti] and not isProtectedSlot(targets[ti].slot) then`,
    `        claimed[ti] = index`,
    `      end`,
    `    end`,
    `  end`,
    `  local lastClaimed = 0`,
    `  for ti in pairs(claimed) do`,
    `    if ti > lastClaimed then lastClaimed = ti end`,
    `  end`,
    `  local leftovers = {}`,
    `  for ti = lastClaimed + 1, #targets do`,
    `    if not isProtectedSlot(targets[ti].slot) then`,
    `      table.insert(leftovers, ti)`,
    `    end`,
    `  end`,
    `  for ti = lastClaimed, 1, -1 do`,
    `    if not claimed[ti] and not isProtectedSlot(targets[ti].slot) then`,
    `      table.insert(leftovers, ti)`,
    `    end`,
    `  end`,
    `  local nextLeftover = 1`,
    `  local bound, placed = 0, 0`,
    `  local skipped, boundOnly = {}, {}`,
    `  local usedToggles = {}`,
    `  st.placements = {}`,
    ``,
    `  local function clearTargetSlot(target)`,
    `    if HasAction(target.slot) then`,
    `      PickupAction(target.slot)`,
    `      ClearCursor()`,
    `    end`,
    `  end`,
    ``,
    `  local function takeTarget(bind, index)`,
    `    local ti = plannedTargetIndex(bind, barCount)`,
    `    if ti and claimed[ti] == index and targets[ti] and not isProtectedSlot(targets[ti].slot) then`,
    `      return targets[ti]`,
    `    end`,
    `    while nextLeftover <= #leftovers do`,
    `      local candidate = leftovers[nextLeftover]`,
    `      nextLeftover = nextLeftover + 1`,
    `      if not isProtectedSlot(targets[candidate].slot) then`,
    `        return targets[candidate]`,
    `      end`,
    `    end`,
    `    return nil`,
    `  end`,
    ``,
    `  for index, bind in ipairs(profile.binds) do`,
    `    local label = string.format("KO%02d", index)`,
    `    if bind.command then`,
    `      bindKeyToCommand(bind.key, bind.command)`,
    `      bound = bound + 1`,
    `      st.placements[index] = { action = bind.command }`,
    `    elseif not bindIsKnown(bind) then`,
    `      local name = bind.name or (bind.spell and resolveSpellName(bind.spell)) or ("spell:" .. tostring(bind.spell))`,
    `      table.insert(skipped, name)`,
    `    else`,
    `      local name = bind.spell and resolveSpellName(bind.spell) or bind.name`,
    `      local body = buildMacroBody(bind, name)`,
    `      local target = takeTarget(bind, index)`,
    `      local onBar = false`,
    `      local usedMacro = nil`,
    `      if body then`,
    `        if makeMacro(label, body) then`,
    `          usedMacro = label`,
    `          if target then`,
    `            clearTargetSlot(target)`,
    `            onBar = placeMacro(label, target)`,
    `          end`,
    `        end`,
    `      elseif bind.spell and target then`,
    `        clearTargetSlot(target)`,
    `        if pickupSpell(bind.spell, name) then`,
    `          onBar = placeVerified(target.slot, nil, bind.spell)`,
    `        end`,
    `        if not onBar and name then`,
    `          if makeMacro(label, buildSpellMacroBody(name)) then`,
    `            usedMacro = label`,
    `            onBar = placeMacro(label, target)`,
    `          end`,
    `        end`,
    `      end`,
    `      if onBar and target then`,
    `        placed = placed + 1`,
    `        if target.toggle then usedToggles[target.toggle] = true end`,
    `        local okCommand = bindKeyToCommand(bind.key, target.command)`,
    `        if not okCommand then`,
    `          if usedMacro then SetBindingMacro(bind.key, usedMacro) elseif name then SetBindingSpell(bind.key, name) end`,
    `        end`,
    `        bound = bound + 1`,
    `        st.placements[index] = { slot = target.slot, action = GetBindingAction(bind.key), macro = usedMacro, spell = (not usedMacro) and bind.spell or nil }`,
    `        decorateButton(target.frame, bind.category, bind.variant)`,
    `      else`,
    `        if usedMacro then`,
    `          SetBindingMacro(bind.key, usedMacro)`,
    `          bound = bound + 1`,
    `        elseif name then`,
    `          SetBindingSpell(bind.key, name)`,
    `          bound = bound + 1`,
    `        end`,
    `        st.placements[index] = { action = GetBindingAction(bind.key) }`,
    `        table.insert(boundOnly, (name or bind.key) .. " (" .. bind.key .. ")")`,
    `      end`,
    `    end`,
    `  end`,
    `  local wantedSlots = claimedSlotSet(st)`,
    `  for _, target in ipairs(targets) do`,
    `    if not wantedSlots[target.slot] and HasAction(target.slot) and not isProtectedSlot(target.slot) then`,
    `      PickupAction(target.slot)`,
    `      ClearCursor()`,
    `    end`,
    `  end`,
    `  SaveBindings(GetCurrentBindingSet())`,
    `  st.hash = profile.hash`,
    `  lastUsedToggles = usedToggles`,
    `  updateLegend()`,
    `  refreshAllMacroNames()`,
    `  if updateBrowser then updateBrowser() end`,
    `  printMsg(string.format(UI.msgApplied, bound, placed))`,
    `  if adapted then`,
    `    printMsg(UI.msgSpecAdapted)`,
    `  end`,
    `  if #skipped > 0 then`,
    `    printMsg(string.format(UI.msgSkipped, table.concat(skipped, ", ")))`,
    `  end`,
    `  if #boundOnly > 0 then`,
    `    printMsg(string.format(UI.msgBoundOnly, table.concat(boundOnly, ", ")))`,
    `  end`,
    `  if GetCurrentBindingSet and GetCurrentBindingSet() == 1 and not chardb().warnedAccountBinds then`,
    `    chardb().warnedAccountBinds = true`,
    `    printMsg(UI.msgAccountBinds)`,
    `  end`,
    `  if GetActionBarToggles then`,
    `    local toggles = { GetActionBarToggles() }`,
    `    local anyHidden = false`,
    `    for barNumber = 1, 4 do`,
    `      if usedToggles[barNumber] and not toggles[barNumber] then anyHidden = true end`,
    `    end`,
    `    if anyHidden then`,
    `      printMsg(UI.enableBarsHint)`,
    `    end`,
    `  end`,
    `end`,
    ``,
    `local restoreQueued = nil`,
    ``,
    `local function restoreBackup(index)`,
    `  local c = chardb()`,
    `  local snapshot = c.backups[index]`,
    `  if not snapshot then return end`,
    `  if InCombatLockdown() then`,
    `    restoreQueued = index`,
    `    printMsg(UI.msgCombat)`,
    `    return`,
    `  end`,
    `  for macroLabel, macroBody in pairs(snapshot.macroBodies or {}) do`,
    `    if macroBody and macroBody ~= "" then`,
    `      makeMacro(macroLabel, macroBody)`,
    `    end`,
    `  end`,
    `  clearOwnedButtons()`,
    `  for _, bar in ipairs(BARS) do`,
    `    for i = 1, BAR_SIZE do`,
    `      local slot = bar.base + i`,
    `      local wantedSpell = snapshot.slots[slot]`,
    `      local wantedMacro = snapshot.macros and snapshot.macros[slot]`,
    `      local actionType, id = GetActionInfo(slot)`,
    `      if wantedMacro then`,
    `        if not isProtectedSlot(slot) then`,
    `          if HasAction(slot) then`,
    `            PickupAction(slot)`,
    `            ClearCursor()`,
    `          end`,
    `          placeMacro(wantedMacro, { slot = slot })`,
    `        end`,
    `      elseif wantedSpell then`,
    `        if not (actionType == "spell" and actionMatchesSpell(id, wantedSpell)) and not isProtectedSlot(slot) then`,
    `          if HasAction(slot) then`,
    `            PickupAction(slot)`,
    `            ClearCursor()`,
    `          end`,
    `          if pickupSpell(wantedSpell, resolveSpellName(wantedSpell)) then`,
    `            PlaceAction(slot)`,
    `            ClearCursor()`,
    `          end`,
    `        end`,
    `      elseif actionType == "spell" and not isProtectedSlot(slot) then`,
    `        PickupAction(slot)`,
    `        ClearCursor()`,
    `      end`,
    `    end`,
    `  end`,
    `  for key, action in pairs(snapshot.binds) do`,
    `    if action == "" then`,
    `      SetBinding(key)`,
    `    else`,
    `      SetBinding(key, action)`,
    `    end`,
    `  end`,
    `  SaveBindings(GetCurrentBindingSet())`,
    `  specState().hash = nil`,
    `  refreshAllMacroNames()`,
    `  printMsg(string.format(UI.msgRestored, snapshot.name .. " " .. snapshot.at))`,
    `  if updateBrowser then updateBrowser() end`,
    `end`,
    ``,
    `local function runCheck()`,
    `  if verifyApplied(currentProfile()) then`,
    `    printMsg(UI.msgCheckOk)`,
    `  else`,
    `    printMsg(UI.msgCheckDrift)`,
    `  end`,
    `end`,
    ``,
    `local function clearMainBar()`,
    `  if InCombatLockdown() then`,
    `    printMsg(UI.msgCombat)`,
    `    return`,
    `  end`,
    `  for slot = 1, 12 do`,
    `    if HasAction(slot) and not isProtectedSlot(slot) then`,
    `      PickupAction(slot)`,
    `      ClearCursor()`,
    `    end`,
    `  end`,
    `  printMsg(UI.msgCleared)`,
    `end`,
    ``,
    `local function enableExtraBars()`,
    `  if InCombatLockdown() then`,
    `    printMsg(UI.msgCombat)`,
    `    return`,
    `  end`,
    `  local ok = false`,
    `  if C_EditMode and C_EditMode.GetLayouts and C_EditMode.SaveLayouts and Enum and Enum.EditModeSystem then`,
    `    local success, layouts = pcall(C_EditMode.GetLayouts)`,
    `    if success and layouts and layouts.layouts then`,
    `      local active = layouts.layouts[layouts.activeLayout]`,
    `      local presetType = Enum.EditModeLayoutType and Enum.EditModeLayoutType.Preset`,
    `      if active and active.layoutType ~= presetType then`,
    `        local visibleSetting = Enum.EditModeActionBarSetting and Enum.EditModeActionBarSetting.VisibleSetting`,
    `        local changed = false`,
    `        local allVisible = true`,
    `        for _, system in ipairs(active.systems or {}) do`,
    `          if system.system == Enum.EditModeSystem.ActionBar and system.systemIndex and system.systemIndex >= 2 and system.systemIndex <= 5 then`,
    `            local found = false`,
    `            system.settings = system.settings or {}`,
    `            for _, setting in ipairs(system.settings) do`,
    `              if visibleSetting and setting.setting == visibleSetting then`,
    `                found = true`,
    `                if setting.value == 3 then`,
    `                  setting.value = 0`,
    `                  changed = true`,
    `                end`,
    `              end`,
    `            end`,
    `            if not found and visibleSetting then`,
    `              table.insert(system.settings, { setting = visibleSetting, value = 0 })`,
    `              changed = true`,
    `            end`,
    `          end`,
    `        end`,
    `        if changed then`,
    `          if pcall(C_EditMode.SaveLayouts, layouts) then ok = true end`,
    `        elseif allVisible then`,
    `          ok = true`,
    `        end`,
    `      end`,
    `    end`,
    `  end`,
    `  if not ok and SetActionBarToggles then`,
    `    if pcall(SetActionBarToggles, true, true, true, true, true, true, true) then ok = true end`,
    `  end`,
    `  if ok then`,
    `    printMsg(UI.msgBarsEnabled)`,
    `  else`,
    `    printMsg(UI.msgBarsManual)`,
    `  end`,
    `end`,
    ``,
    `local function bindIcon(bind)`,
    `  if bind.spell and C_Spell and C_Spell.GetSpellTexture then`,
    `    local icon = C_Spell.GetSpellTexture(bind.spell)`,
    `    if icon then return icon end`,
    `  end`,
    `  if bind.item and GetInventoryItemTexture then`,
    `    local icon = GetInventoryItemTexture("player", bind.item)`,
    `    if icon then return icon end`,
    `  end`,
    `  return QUESTION_ICON`,
    `end`,
    ``,
    `local function bindDisplayName(bind)`,
    `  if bind.spell then`,
    `    return resolveSpellName(bind.spell) or bind.name or ("#" .. bind.spell)`,
    `  end`,
    `  return bind.name or bind.key`,
    `end`,
    ``,
    `local function shortKey(key)`,
    `  local text = key`,
    `  text = string.gsub(text, "SHIFT%-", "s")`,
    `  text = string.gsub(text, "CTRL%-", "c")`,
    `  text = string.gsub(text, "ALT%-", "a")`,
    `  text = string.gsub(text, "BUTTON", "M")`,
    `  text = string.gsub(text, "MOUSEWHEELUP", "WU")`,
    `  text = string.gsub(text, "MOUSEWHEELDOWN", "WD")`,
    `  return text`,
    `end`,
    ``,
    `local browser = nil`,
    `local browserSelected = nil`,
    `local browserView = "keys"`,
    `local browserLayer = ""`,
    `local browserCells = {}`,
    `local browserRows = {}`,
    `local browserKeyCells = {}`,
    `local browserBackupRows = {}`,
    `local browserProfileButtons = {}`,
    `local browserViewButtons = {}`,
    `local browserLayerButtons = {}`,
    `local browserKeysOnly = nil`,
    `local browserStatus = nil`,
    `local browserSpecWarning = nil`,
    `local browserApplyButton = nil`,
    `local browserSaveButton = nil`,
    `local browserHistoryHeader = nil`,
    `local browserImportButton = nil`,
    ``,
    `local CELL = 34`,
    `local CELL_GAP = 3`,
    `local PREVIEW_LEFT = 210`,
    `local PREVIEW_TOP = 78`,
    `local KEY_UNIT = 3.4`,
    ``,
    `local function removeImportedProfile(id)`,
    `  if not id then return end`,
    `  local imported = importedProfiles()`,
    `  for index = #imported, 1, -1 do`,
    `    if imported[index].id == id then table.remove(imported, index) end`,
    `  end`,
    `  local c = chardb()`,
    `  for spec, chosen in pairs(c.profileBySpec) do`,
    `    if chosen == id then c.profileBySpec[spec] = nil end`,
    `  end`,
    `  browserSelected = nil`,
    `  if updateBrowser then updateBrowser() end`,
    `end`,
    ``,
    `local function ensureProfileButton(index)`,
    `  local button = browserProfileButtons[index]`,
    `  if button then return button end`,
    `  button = CreateFrame("Button", nil, browser, "BackdropTemplate")`,
    `  button:SetSize(182, 40)`,
    `  button:SetPoint("TOPLEFT", 14, -60 - (index - 1) * 44)`,
    `  button:SetBackdrop({ bgFile = "Interface/Tooltips/UI-Tooltip-Background", edgeFile = "Interface/Tooltips/UI-Tooltip-Border", edgeSize = 10, insets = { left = 2, right = 2, top = 2, bottom = 2 } })`,
    `  local label = button:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")`,
    `  label:SetPoint("TOPLEFT", 8, -6)`,
    `  label:SetPoint("RIGHT", -22, 0)`,
    `  label:SetJustifyH("LEFT")`,
    `  button.koLabel = label`,
    `  local tag = button:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")`,
    `  tag:SetPoint("BOTTOMLEFT", 8, 5)`,
    `  button.koTag = tag`,
    `  local remove = CreateFrame("Button", nil, button, "UIPanelCloseButton")`,
    `  remove:SetSize(18, 18)`,
    `  remove:SetPoint("TOPRIGHT", 0, -2)`,
    `  remove:SetScript("OnClick", function(self)`,
    `    removeImportedProfile(self.koProfileId)`,
    `  end)`,
    `  button.koRemove = remove`,
    `  button:SetScript("OnClick", function(self)`,
    `    browserSelected = self.koIndex`,
    `    updateBrowser()`,
    `  end)`,
    `  browserProfileButtons[index] = button`,
    `  return button`,
    `end`,
    ``,
    `local importFrame = nil`,
    ``,
    `local function acceptImport()`,
    `  if not importFrame then return end`,
    `  local count, err = importFromString(importFrame.koEdit:GetText())`,
    `  if not count then`,
    `    printMsg(err or UI.importErrFormat)`,
    `    return`,
    `  end`,
    `  importFrame.koEdit:SetText("")`,
    `  importFrame:Hide()`,
    `  printMsg(string.format(UI.msgImported, count))`,
    `  browserSelected = #allProfiles()`,
    `  if updateBrowser then updateBrowser() end`,
    `end`,
    ``,
    `local function buildImportDialog()`,
    `  if importFrame then return importFrame end`,
    `  local frame = CreateFrame("Frame", "KeybindOptimizerImport", UIParent, "BackdropTemplate")`,
    `  frame:SetSize(560, 320)`,
    `  frame:SetPoint("CENTER")`,
    `  frame:SetFrameStrata("FULLSCREEN_DIALOG")`,
    `  frame:SetBackdrop({ bgFile = "Interface/Tooltips/UI-Tooltip-Background", edgeFile = "Interface/Tooltips/UI-Tooltip-Border", edgeSize = 14, insets = { left = 4, right = 4, top = 4, bottom = 4 } })`,
    `  frame:SetBackdropColor(0.05, 0.05, 0.07, 0.97)`,
    `  frame:SetMovable(true)`,
    `  frame:EnableMouse(true)`,
    `  frame:RegisterForDrag("LeftButton")`,
    `  frame:SetScript("OnDragStart", frame.StartMoving)`,
    `  frame:SetScript("OnDragStop", frame.StopMovingOrSizing)`,
    `  frame:SetClampedToScreen(true)`,
    `  tinsert(UISpecialFrames, "KeybindOptimizerImport")`,
    `  local title = frame:CreateFontString(nil, "OVERLAY", "GameFontNormalLarge")`,
    `  title:SetPoint("TOPLEFT", 16, -14)`,
    `  title:SetText(UI.importTitle)`,
    `  local hint = frame:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")`,
    `  hint:SetPoint("TOPLEFT", 16, -38)`,
    `  hint:SetPoint("RIGHT", -16, 0)`,
    `  hint:SetJustifyH("LEFT")`,
    `  hint:SetText(UI.importHint)`,
    `  local close = CreateFrame("Button", nil, frame, "UIPanelCloseButton")`,
    `  close:SetPoint("TOPRIGHT", -6, -6)`,
    `  local scroll = CreateFrame("ScrollFrame", nil, frame, "UIPanelScrollFrameTemplate")`,
    `  scroll:SetPoint("TOPLEFT", 16, -64)`,
    `  scroll:SetPoint("BOTTOMRIGHT", -36, 52)`,
    `  local edit = CreateFrame("EditBox", nil, scroll)`,
    `  edit:SetMultiLine(true)`,
    `  edit:SetFontObject(ChatFontNormal)`,
    `  edit:SetWidth(490)`,
    `  edit:SetAutoFocus(true)`,
    `  edit:SetMaxLetters(0)`,
    `  edit:SetScript("OnEscapePressed", function() frame:Hide() end)`,
    `  scroll:SetScrollChild(edit)`,
    `  frame.koEdit = edit`,
    `  local accept = CreateFrame("Button", nil, frame, "UIPanelButtonTemplate")`,
    `  accept:SetSize(150, 24)`,
    `  accept:SetPoint("BOTTOMRIGHT", -16, 14)`,
    `  accept:SetText(UI.importAccept)`,
    `  accept:SetScript("OnClick", acceptImport)`,
    `  local cancel = CreateFrame("Button", nil, frame, "UIPanelButtonTemplate")`,
    `  cancel:SetSize(110, 24)`,
    `  cancel:SetPoint("BOTTOMRIGHT", -172, 14)`,
    `  cancel:SetText(UI.importCancel)`,
    `  cancel:SetScript("OnClick", function() frame:Hide() end)`,
    `  importFrame = frame`,
    `  return frame`,
    `end`,
    ``,
    `local function showImportDialog()`,
    `  local frame = buildImportDialog()`,
    `  frame:Show()`,
    `  frame.koEdit:SetFocus()`,
    `end`,
    ``,
    `local function browserProfileIndex()`,
    `  local index = browserSelected or currentProfileIndex()`,
    `  if index > #allProfiles() then return currentProfileIndex() end`,
    `  return index`,
    `end`,
    ``,
    `local function setCellContent(cell, bind, hotkeyText)`,
    `  cell.koBind = bind`,
    `  cell.koUnknown = nil`,
    `  cell.koHotkey:SetText(hotkeyText or "")`,
    `  if not bind then`,
    `    cell.koIcon:Hide()`,
    `    cell.koStrip:Hide()`,
    `    cell.koNumber:Hide()`,
    `    return`,
    `  end`,
    `  local arenaNumber = bind.command and string.match(bind.command, "^TARGETARENA(%d)$")`,
    `  if arenaNumber then`,
    `    cell.koIcon:Hide()`,
    `    cell.koNumber:SetText(arenaNumber)`,
    `    cell.koNumber:Show()`,
    `  else`,
    `    cell.koNumber:Hide()`,
    `    cell.koIcon:SetTexture(bindIcon(bind))`,
    `    cell.koIcon:Show()`,
    `    if bindIsKnown(bind) then`,
    `      cell.koIcon:SetDesaturated(false)`,
    `      cell.koIcon:SetVertexColor(1, 1, 1)`,
    `    else`,
    `      cell.koIcon:SetDesaturated(true)`,
    `      cell.koIcon:SetVertexColor(1, 0.4, 0.4)`,
    `      cell.koUnknown = true`,
    `    end`,
    `  end`,
    `  local color = bind.category and COLORS[bind.category]`,
    `  if color then`,
    `    local r, g, b = hexColor(color)`,
    `    cell.koStrip:SetColorTexture(r, g, b, 1)`,
    `    cell.koStrip:Show()`,
    `  else`,
    `    cell.koStrip:Hide()`,
    `  end`,
    `end`,
    ``,
    `local function makeCell(parent)`,
    `  local cell = CreateFrame("Frame", nil, parent, "BackdropTemplate")`,
    `  cell:SetBackdrop({ bgFile = "Interface/Tooltips/UI-Tooltip-Background", edgeFile = "Interface/Tooltips/UI-Tooltip-Border", edgeSize = 8, insets = { left = 2, right = 2, top = 2, bottom = 2 } })`,
    `  cell:SetBackdropColor(0.1, 0.1, 0.13, 0.85)`,
    `  local icon = cell:CreateTexture(nil, "ARTWORK")`,
    `  icon:SetPoint("TOPLEFT", 2, -2)`,
    `  icon:SetPoint("BOTTOMRIGHT", -2, 5)`,
    `  icon:SetTexCoord(0.07, 0.93, 0.07, 0.93)`,
    `  cell.koIcon = icon`,
    `  local strip = cell:CreateTexture(nil, "OVERLAY")`,
    `  strip:SetPoint("BOTTOMLEFT", 2, 2)`,
    `  strip:SetPoint("BOTTOMRIGHT", -2, 2)`,
    `  strip:SetHeight(3)`,
    `  cell.koStrip = strip`,
    `  local number = cell:CreateFontString(nil, "OVERLAY", "GameFontNormalLarge")`,
    `  number:SetPoint("CENTER", 0, 1)`,
    `  cell.koNumber = number`,
    `  local hotkey = cell:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")`,
    `  hotkey:SetPoint("TOPRIGHT", -1, -1)`,
    `  hotkey:SetScale(0.82)`,
    `  cell.koHotkey = hotkey`,
    `  cell:EnableMouse(true)`,
    `  cell:SetScript("OnEnter", function(self)`,
    `    if not self.koBind then return end`,
    `    GameTooltip:SetOwner(self, "ANCHOR_RIGHT")`,
    `    local shownSpell = false`,
    `    if self.koBind.spell then`,
    `      shownSpell = pcall(GameTooltip.SetSpellByID, GameTooltip, self.koBind.spell)`,
    `    end`,
    `    if not shownSpell then`,
    `      GameTooltip:SetText(bindDisplayName(self.koBind))`,
    `    end`,
    `    GameTooltip:AddLine(self.koBind.key, 0.7, 0.7, 1)`,
    `    if self.koBind.category then`,
    `      local color = COLORS[self.koBind.category]`,
    `      if color then`,
    `        local r, g, b = hexColor(color)`,
    `        GameTooltip:AddLine(noteFor(self.koBind.category, self.koBind.variant), r, g, b)`,
    `      end`,
    `    end`,
    `    if self.koUnknown then`,
    `      GameTooltip:AddLine(UI.unknownTag, 1, 0.35, 0.35)`,
    `    end`,
    `    GameTooltip:Show()`,
    `  end)`,
    `  cell:SetScript("OnLeave", function() GameTooltip:Hide() end)`,
    `  return cell`,
    `end`,
    ``,
    `local updateKeyboardView`,
    ``,
    `local function buildBrowser()`,
    `  if browser then return browser end`,
    `  local leftHeight = 120 + #PROFILES * 44 + 36 + 5 * 30`,
    `  local frame = CreateFrame("Frame", "KeybindOptimizerBrowser", UIParent, "BackdropTemplate")`,
    `  frame:SetSize(940, math.max(630, leftHeight))`,
    `  frame:SetPoint("CENTER")`,
    `  frame:SetFrameStrata("DIALOG")`,
    `  frame:SetBackdrop({ bgFile = "Interface/Tooltips/UI-Tooltip-Background", edgeFile = "Interface/Tooltips/UI-Tooltip-Border", edgeSize = 14, insets = { left = 4, right = 4, top = 4, bottom = 4 } })`,
    `  frame:SetBackdropColor(0.05, 0.05, 0.07, 0.96)`,
    `  frame:SetMovable(true)`,
    `  frame:EnableMouse(true)`,
    `  frame:RegisterForDrag("LeftButton")`,
    `  frame:SetScript("OnDragStart", frame.StartMoving)`,
    `  frame:SetScript("OnDragStop", frame.StopMovingOrSizing)`,
    `  frame:SetClampedToScreen(true)`,
    `  tinsert(UISpecialFrames, "KeybindOptimizerBrowser")`,
    ``,
    `  local title = frame:CreateFontString(nil, "OVERLAY", "GameFontNormalLarge")`,
    `  title:SetPoint("TOPLEFT", 16, -14)`,
    `  title:SetText(UI.browserTitle)`,
    ``,
    `  local close = CreateFrame("Button", nil, frame, "UIPanelCloseButton")`,
    `  close:SetPoint("TOPRIGHT", -6, -6)`,
    ``,
    `  local profilesHeader = frame:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")`,
    `  profilesHeader:SetPoint("TOPLEFT", 16, -46)`,
    `  profilesHeader:SetText(UI.profilesHeader)`,
    ``,
    `  local function makeTab(label, width, x, onClick)`,
    `    local tab = CreateFrame("Button", nil, frame, "UIPanelButtonTemplate")`,
    `    tab:SetSize(width, 22)`,
    `    tab:SetPoint("TOPLEFT", x, -46)`,
    `    tab:SetText(label)`,
    `    tab:SetScript("OnClick", onClick)`,
    `    return tab`,
    `  end`,
    `  browserViewButtons[1] = makeTab(UI.viewKeyboard, 110, PREVIEW_LEFT, function()`,
    `    browserView = "keys"`,
    `    updateBrowser()`,
    `  end)`,
    `  browserViewButtons[2] = makeTab(UI.viewBars, 110, PREVIEW_LEFT + 114, function()`,
    `    browserView = "bars"`,
    `    updateBrowser()`,
    `  end)`,
    `  local layerDefs = {`,
    `    { label = UI.layerBase, prefix = "" },`,
    `    { label = "Shift", prefix = "SHIFT-" },`,
    `    { label = "Ctrl", prefix = "CTRL-" },`,
    `    { label = "Alt", prefix = "ALT-" },`,
    `  }`,
    `  for index, def in ipairs(layerDefs) do`,
    `    local tab = makeTab(def.label, 62, PREVIEW_LEFT + 248 + (index - 1) * 66, function()`,
    `      browserLayer = def.prefix`,
    `      updateBrowser()`,
    `    end)`,
    `    tab.koPrefix = def.prefix`,
    `    browserLayerButtons[index] = tab`,
    `  end`,
    ``,
    `  for row = 0, 7 do`,
    `    local rowLabel = frame:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")`,
    `    rowLabel:SetPoint("TOPLEFT", PREVIEW_LEFT, -(PREVIEW_TOP - 12) - row * (CELL + CELL_GAP + 14))`,
    `    browserRows[row + 1] = rowLabel`,
    `    for col = 0, BAR_SIZE - 1 do`,
    `      local cell = makeCell(frame)`,
    `      cell:SetSize(CELL, CELL)`,
    `      cell:SetPoint("TOPLEFT", PREVIEW_LEFT + col * (CELL + CELL_GAP), -PREVIEW_TOP - row * (CELL + CELL_GAP + 14))`,
    `      browserCells[row * BAR_SIZE + col + 1] = cell`,
    `    end`,
    `  end`,
    ``,
    `  browserImportButton = CreateFrame("Button", nil, frame, "UIPanelButtonTemplate")`,
    `  browserImportButton:SetSize(182, 22)`,
    `  browserImportButton:SetText(UI.importButton)`,
    `  browserImportButton:SetScript("OnClick", showImportDialog)`,
    ``,
    `  local historyTop = 60 + #PROFILES * 44 + 40`,
    `  browserHistoryHeader = frame:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")`,
    `  browserHistoryHeader:SetPoint("TOPLEFT", 16, -historyTop)`,
    `  browserHistoryHeader:SetText(UI.historyHeader)`,
    `  for i = 1, 5 do`,
    `    local rowFrame = CreateFrame("Frame", nil, frame)`,
    `    rowFrame:SetSize(182, 28)`,
    `    rowFrame:SetPoint("TOPLEFT", 14, -(historyTop + 14 + (i - 1) * 30))`,
    `    local label = rowFrame:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")`,
    `    label:SetPoint("TOPLEFT", 2, 0)`,
    `    label:SetPoint("RIGHT", -2, 0)`,
    `    label:SetJustifyH("LEFT")`,
    `    label:SetWordWrap(false)`,
    `    rowFrame.koLabel = label`,
    `    local restore = CreateFrame("Button", nil, rowFrame, "UIPanelButtonTemplate")`,
    `    restore:SetSize(96, 15)`,
    `    restore:SetPoint("TOPLEFT", 2, -12)`,
    `    restore:SetText(UI.restoreButton)`,
    `    restore:GetFontString():SetScale(0.78)`,
    `    restore:SetScript("OnClick", function()`,
    `      if rowFrame.koIndex then restoreBackup(rowFrame.koIndex) end`,
    `    end)`,
    `    local remove = CreateFrame("Button", nil, rowFrame, "UIPanelButtonTemplate")`,
    `    remove:SetSize(20, 15)`,
    `    remove:SetPoint("TOPLEFT", 102, -12)`,
    `    remove:SetText("X")`,
    `    remove:GetFontString():SetScale(0.78)`,
    `    remove:SetScript("OnClick", function()`,
    `      if rowFrame.koIndex then`,
    `        table.remove(chardb().backups, rowFrame.koIndex)`,
    `        updateBrowser()`,
    `      end`,
    `    end)`,
    `    browserBackupRows[i] = rowFrame`,
    `  end`,
    ``,
    `  browserSpecWarning = frame:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")`,
    `  browserSpecWarning:SetPoint("BOTTOMLEFT", PREVIEW_LEFT, 66)`,
    `  browserSpecWarning:SetTextColor(1, 0.45, 0.35)`,
    ``,
    `  browserKeysOnly = frame:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")`,
    `  browserKeysOnly:SetPoint("BOTTOMLEFT", PREVIEW_LEFT, 84)`,
    `  browserKeysOnly:SetPoint("RIGHT", -16, 0)`,
    `  browserKeysOnly:SetJustifyH("LEFT")`,
    ``,
    `  browserStatus = frame:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")`,
    `  browserStatus:SetPoint("BOTTOMLEFT", PREVIEW_LEFT, 22)`,
    ``,
    `  browserSaveButton = CreateFrame("Button", nil, frame, "UIPanelButtonTemplate")`,
    `  browserSaveButton:SetSize(190, 26)`,
    `  browserSaveButton:SetPoint("BOTTOMRIGHT", -168, 16)`,
    `  browserSaveButton:SetText(UI.backupSave)`,
    `  browserSaveButton:SetScript("OnClick", function()`,
    `    local snapshot = captureBackup(UI.backupManual)`,
    `    printMsg(string.format(UI.msgBackupSaved, snapshot.at))`,
    `    updateBrowser()`,
    `  end)`,
    ``,
    `  browserApplyButton = CreateFrame("Button", nil, frame, "UIPanelButtonTemplate")`,
    `  browserApplyButton:SetSize(140, 26)`,
    `  browserApplyButton:SetPoint("BOTTOMRIGHT", -16, 16)`,
    `  browserApplyButton:SetText(UI.applyButton)`,
    `  browserApplyButton:SetScript("OnClick", function()`,
    `    local selected = allProfiles()[browserProfileIndex()]`,
    `    if selected then chardb().profileBySpec[specKey()] = selected.id end`,
    `    apply("manual")`,
    `    updateBrowser()`,
    `  end)`,
    ``,
    `  local function makeCommandButton(width, offsetX, label, onClick)`,
    `    local button = CreateFrame("Button", nil, frame, "UIPanelButtonTemplate")`,
    `    button:SetSize(width, 22)`,
    `    button:SetPoint("BOTTOMRIGHT", offsetX, 46)`,
    `    button:SetText(label)`,
    `    button:SetScript("OnClick", onClick)`,
    `    return button`,
    `  end`,
    `  makeCommandButton(130, -16, UI.checkButton, function()`,
    `    runCheck()`,
    `    updateBrowser()`,
    `  end)`,
    `  makeCommandButton(170, -150, UI.forceButton, function()`,
    `    apply("force")`,
    `    updateBrowser()`,
    `  end)`,
    `  makeCommandButton(150, -324, UI.barsButton, enableExtraBars)`,
    `  makeCommandButton(150, -478, UI.clearMainButton, clearMainBar)`,
    ``,
    `  browser = frame`,
    `  return frame`,
    `end`,
    ``,
    `updateKeyboardView = function(profile)`,
    `  local keyboard = profile.keyboard or KEYBOARDS[profile.kb or 1] or KEYBOARDS[1]`,
    `  if not keyboard then return end`,
    `  local bindMap = {}`,
    `  for _, bind in ipairs(profile.binds) do`,
    `    bindMap[bind.key] = bind`,
    `  end`,
    `  local n = 0`,
    `  for rowIndex, row in ipairs(keyboard) do`,
    `    for _, key in ipairs(row) do`,
    `      n = n + 1`,
    `      local cell = browserKeyCells[n]`,
    `      if not cell then`,
    `        cell = makeCell(browser)`,
    `        browserKeyCells[n] = cell`,
    `      end`,
    `      cell:ClearAllPoints()`,
    `      cell:SetPoint("TOPLEFT", PREVIEW_LEFT + key.x * KEY_UNIT, -(PREVIEW_TOP + (rowIndex - 1) * (CELL + 4)))`,
    `      cell:SetSize(math.max(18, key.w * KEY_UNIT - 3), CELL)`,
    `      cell:Show()`,
    `      local bind = nil`,
    `      if not (key.m and browserLayer == "") then`,
    `        bind = bindMap[browserLayer .. key.k]`,
    `      end`,
    `      setCellContent(cell, bind, key.label)`,
    `      if key.m then`,
    `        cell:SetBackdropColor(0.05, 0.05, 0.06, 0.5)`,
    `      else`,
    `        cell:SetBackdropColor(0.1, 0.1, 0.13, 0.85)`,
    `      end`,
    `    end`,
    `  end`,
    `  for i = n + 1, #browserKeyCells do`,
    `    browserKeyCells[i]:Hide()`,
    `  end`,
    `end`,
    ``,
    `updateBrowser = function()`,
    `  if not browser or not browser:IsShown() then return end`,
    `  local profiles = allProfiles()`,
    `  local index = browserProfileIndex()`,
    `  local profile = profiles[index]`,
    `  if not profile then return end`,
    `  local st = specState()`,
    `  local activeIndex = currentProfileIndex()`,
    `  for buttonIndex, rowProfile in ipairs(profiles) do`,
    `    local button = ensureProfileButton(buttonIndex)`,
    `    button:Show()`,
    `    button.koIndex = buttonIndex`,
    `    button.koLabel:SetText(rowProfile.name)`,
    `    local isSelected = buttonIndex == index`,
    `    button:SetBackdropColor(isSelected and 0.22 or 0.1, isSelected and 0.2 or 0.1, isSelected and 0.35 or 0.14, 0.9)`,
    `    local tags = {}`,
    `    if buttonIndex == activeIndex then table.insert(tags, UI.activeTag) end`,
    `    if rowProfile.hash == st.hash then table.insert(tags, UI.appliedTag) end`,
    `    if rowProfile.imported then table.insert(tags, UI.importedTag) end`,
    `    button.koTag:SetText(table.concat(tags, " · "))`,
    `    button.koRemove:SetShown(rowProfile.imported == true)`,
    `    button.koRemove.koProfileId = rowProfile.id`,
    `  end`,
    `  for buttonIndex = #profiles + 1, #browserProfileButtons do`,
    `    browserProfileButtons[buttonIndex]:Hide()`,
    `  end`,
    `  local listBottom = 60 + #profiles * 44`,
    `  browserImportButton:ClearAllPoints()`,
    `  browserImportButton:SetPoint("TOPLEFT", 14, -(listBottom + 4))`,
    `  local historyTop = listBottom + 40`,
    `  browserHistoryHeader:ClearAllPoints()`,
    `  browserHistoryHeader:SetPoint("TOPLEFT", 16, -historyTop)`,
    `  for i = 1, 5 do`,
    `    local rowFrame = browserBackupRows[i]`,
    `    rowFrame:ClearAllPoints()`,
    `    rowFrame:SetPoint("TOPLEFT", 14, -(historyTop + 14 + (i - 1) * 30))`,
    `  end`,
    `  browser:SetHeight(math.max(630, historyTop + 14 + 5 * 30 + 60))`,
    `  browserViewButtons[1]:SetEnabled(browserView ~= "keys")`,
    `  browserViewButtons[2]:SetEnabled(browserView ~= "bars")`,
    `  for _, tab in ipairs(browserLayerButtons) do`,
    `    tab:SetShown(browserView == "keys")`,
    `    tab:SetEnabled(tab.koPrefix ~= browserLayer)`,
    `  end`,
    `  local maxRow = -1`,
    `  local cellBinds = {}`,
    `  local keysOnly = {}`,
    `  for _, bind in ipairs(profile.binds) do`,
    `    if bind.slot ~= nil then`,
    `      cellBinds[bind.slot + 1] = bind`,
    `      local row = math.floor(bind.slot / BAR_SIZE)`,
    `      if row > maxRow then maxRow = row end`,
    `    else`,
    `      table.insert(keysOnly, shortKey(bind.key) .. " — " .. bindDisplayName(bind))`,
    `    end`,
    `  end`,
    `  if browserView == "keys" then`,
    `    for i = 1, #browserCells do`,
    `      browserCells[i]:Hide()`,
    `    end`,
    `    for i = 1, #browserRows do`,
    `      browserRows[i]:SetText("")`,
    `    end`,
    `    updateKeyboardView(profile)`,
    `  else`,
    `    for i = 1, #browserKeyCells do`,
    `      browserKeyCells[i]:Hide()`,
    `    end`,
    `    for row = 0, 7 do`,
    `      local rowLabel = browserRows[row + 1]`,
    `      rowLabel:SetText(row <= maxRow and (row + 1) or "")`,
    `      for col = 0, BAR_SIZE - 1 do`,
    `        local cell = browserCells[row * BAR_SIZE + col + 1]`,
    `        local bind = cellBinds[row * BAR_SIZE + col + 1]`,
    `        cell:SetShown(row <= maxRow)`,
    `        setCellContent(cell, bind, bind and shortKey(bind.key) or "")`,
    `      end`,
    `    end`,
    `  end`,
    `  if #keysOnly > 0 then`,
    `    browserKeysOnly:SetText(UI.keysOnlyHeader .. ": " .. table.concat(keysOnly, "   "))`,
    `  else`,
    `    browserKeysOnly:SetText("")`,
    `  end`,
    `  local c = chardb()`,
    `  for i = 1, 5 do`,
    `    local rowFrame = browserBackupRows[i]`,
    `    local backupIndex = #c.backups - i + 1`,
    `    local snapshot = c.backups[backupIndex]`,
    `    if snapshot then`,
    `      rowFrame:Show()`,
    `      rowFrame.koIndex = backupIndex`,
    `      rowFrame.koLabel:SetText(snapshot.at .. " · " .. snapshot.name)`,
    `    else`,
    `      rowFrame:Hide()`,
    `      rowFrame.koIndex = nil`,
    `    end`,
    `  end`,
    `  browserHistoryHeader:SetShown(#c.backups > 0)`,
    `  browserSpecWarning:SetText(specMatches(profile) and "" or UI.specMismatch)`,
    `  if profile.hash == st.hash then`,
    `    browserStatus:SetText(UI.appliedTag)`,
    `  else`,
    `    browserStatus:SetText("")`,
    `  end`,
    `end`,
    ``,
    `local function toggleBrowser()`,
    `  local frame = buildBrowser()`,
    `  if frame:IsShown() then`,
    `    frame:Hide()`,
    `  else`,
    `    browserSelected = currentProfileIndex()`,
    `    frame:Show()`,
    `    updateBrowser()`,
    `  end`,
    `end`,
    ``,
    `local function makeCheck(panel, y, label, tooltip, key, onToggle)`,
    `  local cb = CreateFrame("CheckButton", nil, panel, "UICheckButtonTemplate")`,
    `  cb:SetPoint("TOPLEFT", 18, y)`,
    `  local fs = panel:CreateFontString(nil, "ARTWORK", "GameFontHighlight")`,
    `  fs:SetPoint("LEFT", cb, "RIGHT", 4, 0)`,
    `  fs:SetText(label)`,
    `  cb:SetChecked(db()[key] and true or false)`,
    `  cb.tooltipText = tooltip`,
    `  cb:SetScript("OnClick", function(self)`,
    `    local checked = self:GetChecked() and true or false`,
    `    db()[key] = checked`,
    `    if onToggle then onToggle(checked) end`,
    `  end)`,
    `  optChecks[key] = cb`,
    `  return cb`,
    `end`,
    ``,
    `local function buildOptions()`,
    `  local panel = CreateFrame("Frame")`,
    `  panel.name = UI.optionsTitle`,
    `  local title = panel:CreateFontString(nil, "ARTWORK", "GameFontNormalLarge")`,
    `  title:SetPoint("TOPLEFT", 16, -16)`,
    `  title:SetText(UI.optionsTitle)`,
    `  makeCheck(panel, -52, UI.autoApplyLabel, UI.autoApplyTooltip, "autoApply")`,
    `  makeCheck(panel, -84, UI.colorsLabel, UI.colorsTooltip, "decor", function(checked)`,
    `    setDecorShown(checked)`,
    `    updateLegend()`,
    `  end)`,
    `  makeCheck(panel, -116, UI.legendLabel, UI.legendTooltip, "legend", function()`,
    `    updateLegend()`,
    `  end)`,
    `  makeCheck(panel, -148, UI.mainbarLabel, UI.mainbarTooltip, "mainbar", invalidateApplied)`,
    `  makeCheck(panel, -180, UI.mouseoverLabel, UI.mouseoverTooltip, "mouseover", invalidateApplied)`,
    `  local function makePanelButton(x, y, label, onClick)`,
    `    local button = CreateFrame("Button", nil, panel, "UIPanelButtonTemplate")`,
    `    button:SetSize(180, 26)`,
    `    button:SetPoint("TOPLEFT", x, y)`,
    `    button:SetText(label)`,
    `    button:SetScript("OnClick", onClick)`,
    `    return button`,
    `  end`,
    `  makePanelButton(16, -224, UI.openBrowser, toggleBrowser)`,
    `  makePanelButton(206, -224, UI.applyNow, function() apply("manual") end)`,
    `  makePanelButton(16, -256, UI.forceButton, function() apply("force") end)`,
    `  makePanelButton(206, -256, UI.checkButton, runCheck)`,
    `  makePanelButton(16, -288, UI.barsButton, enableExtraBars)`,
    `  makePanelButton(206, -288, UI.clearMainButton, clearMainBar)`,
    `  if Settings and Settings.RegisterCanvasLayoutCategory then`,
    `    local category = Settings.RegisterCanvasLayoutCategory(panel, UI.optionsTitle)`,
    `    category.ID = UI.optionsTitle`,
    `    Settings.RegisterAddOnCategory(category)`,
    `  elseif InterfaceOptions_AddCategory then`,
    `    InterfaceOptions_AddCategory(panel)`,
    `  end`,
    `end`,
    ``,
    `local function selectProfile(index)`,
    `  local profile = allProfiles()[index]`,
    `  if not profile then return end`,
    `  chardb().profileBySpec[specKey()] = profile.id`,
    `  browserSelected = index`,
    `  printMsg(string.format(UI.msgProfile, profile.name))`,
    `  apply("manual")`,
    `end`,
    ``,
    `local function handleCommand(message)`,
    `  local command, rest = string.match(message or "", "^%s*(%S*)%s*(.-)%s*$")`,
    `  command = string.lower(command or "")`,
    `  if command == "" then`,
    `    toggleBrowser()`,
    `  elseif command == "apply" then`,
    `    apply("manual")`,
    `  elseif command == "force" then`,
    `    apply("force")`,
    `  elseif command == "check" then`,
    `    runCheck()`,
    `  elseif command == "profile" then`,
    `    selectProfile(tonumber(rest) or 0)`,
    `  elseif command == "auto" then`,
    `    db().autoApply = not db().autoApply`,
    `    syncOptions()`,
    `    printMsg(string.format(UI.msgAuto, stateText(db().autoApply)))`,
    `  elseif command == "mouseover" then`,
    `    db().mouseover = not db().mouseover`,
    `    invalidateApplied()`,
    `    syncOptions()`,
    `    printMsg(string.format(UI.msgMouseover, stateText(db().mouseover)))`,
    `  elseif command == "colors" then`,
    `    db().decor = not db().decor`,
    `    setDecorShown(db().decor)`,
    `    updateLegend()`,
    `    syncOptions()`,
    `    printMsg(string.format(UI.msgColors, stateText(db().decor)))`,
    `  elseif command == "legend" then`,
    `    db().legend = not db().legend`,
    `    updateLegend()`,
    `    syncOptions()`,
    `    printMsg(string.format(UI.msgLegend, stateText(db().legend)))`,
    `  elseif command == "clearmain" then`,
    `    clearMainBar()`,
    `  elseif command == "import" then`,
    `    showImportDialog()`,
    `  elseif command == "bars" then`,
    `    enableExtraBars()`,
    `  elseif command == "mainbar" then`,
    `    db().mainbar = not db().mainbar`,
    `    invalidateApplied()`,
    `    syncOptions()`,
    `    printMsg(string.format(UI.msgMainbar, stateText(db().mainbar)))`,
    `  elseif command == "help" then`,
    `    printMsg(UI.help)`,
    `  else`,
    `    apply("manual")`,
    `  end`,
    `end`,
    ``,
    `local eventFrame = CreateFrame("Frame")`,
    `eventFrame:RegisterEvent("PLAYER_ENTERING_WORLD")`,
    `eventFrame:RegisterEvent("PLAYER_REGEN_ENABLED")`,
    `eventFrame:RegisterEvent("TRAIT_CONFIG_UPDATED")`,
    `eventFrame:RegisterEvent("ACTIVE_PLAYER_SPECIALIZATION_CHANGED")`,
    `eventFrame:RegisterEvent("ACTIONBAR_SLOT_CHANGED")`,
    `local optionsBuilt = false`,
    `local booted = false`,
    `local autoPending = false`,
    `local function scheduleAuto()`,
    `  if not booted or not db().autoApply or autoPending then return end`,
    `  autoPending = true`,
    `  C_Timer.After(1.5, function()`,
    `    autoPending = false`,
    `    apply("auto")`,
    `  end)`,
    `end`,
    `eventFrame:SetScript("OnEvent", function(_, event, arg1, arg2)`,
    `  if event == "PLAYER_ENTERING_WORLD" then`,
    `    db()`,
    `    chardb()`,
    `    if not optionsBuilt then`,
    `      optionsBuilt = true`,
    `      pcall(buildOptions)`,
    `    end`,
    `    if arg1 or arg2 then`,
    `      C_Timer.After(2, function()`,
    `        booted = true`,
    `        if db().autoApply then apply("auto") end`,
    `        refreshAllMacroNames()`,
    `      end)`,
    `    else`,
    `      booted = true`,
    `      scheduleMacroNameRefresh()`,
    `    end`,
    `  elseif event == "ACTIONBAR_SLOT_CHANGED" then`,
    `    scheduleMacroNameRefresh()`,
    `  elseif event == "PLAYER_REGEN_ENABLED" then`,
    `    if applyQueued then`,
    `      local mode = applyQueued`,
    `      applyQueued = nil`,
    `      apply(mode)`,
    `    end`,
    `    if restoreQueued then`,
    `      local queuedIndex = restoreQueued`,
    `      restoreQueued = nil`,
    `      restoreBackup(queuedIndex)`,
    `    end`,
    `  elseif event == "ACTIVE_PLAYER_SPECIALIZATION_CHANGED" then`,
    `    if booted then`,
    `      local profile = currentProfile()`,
    `      if profile and db().autoApply and specMatches(profile) then`,
    `        printMsg(string.format(UI.msgSpecSwitched, profile.name))`,
    `      end`,
    `      scheduleAuto()`,
    `    end`,
    `  elseif event == "TRAIT_CONFIG_UPDATED" then`,
    `    scheduleAuto()`,
    `  end`,
    `end)`,
    ``,
    `SLASH_KEYBINDOPT1 = "/kbo"`,
    `SlashCmdList["KEYBINDOPT"] = handleCommand`,
  ].join('\n')
}

export function interfaceVersionFromBuild(gameBuild: string): string {
  const [major = '1', minor = '0', patch = '0'] = gameBuild.split('.')
  return `${major}${minor.padStart(2, '0')}${patch.padStart(2, '0')}`
}

export function renderAddonToc(addonName: string, gameBuild: string): string {
  return [
    `## Interface: ${interfaceVersionFromBuild(gameBuild)}`,
    `## Title: Keybind Optimizer`,
    `## Notes: Applies a generated keybind layout`,
    `## Version: 2.2.0`,
    `## SavedVariables: KeybindOptimizerDB`,
    `## SavedVariablesPerCharacter: KeybindOptimizerCharDB`,
    ``,
    `${addonName}.lua`,
  ].join('\n')
}
